### ISSUE TITLE
[Anti-adblock] yesmangasbr.com

### ISSUE THREAD

**Issue by J41319** [NanoAdblocker/NanoFilters#335] opened 2019-05-21 23:04 UTC
### URLs where this issue occurs (Required)
https://www.yesmangasbr.com/

### Screenshots (Required)

https://i.imgur.com/5K0ovIy.png
### Screenshot of console (Required, press `F12` to open the console)

https://i.imgur.com/OIbjegI.png
### Describe the issue (Optional if obvious)

The site detects that I'm using an Adblock.

#### Environment (Required)

- Operating System and Version: Windows 10 Enterprise 1809
- Browser and Version: Firefox 69.0a1
- Nano Defender Version: 15.0.0.147 (using uBlock Origin 1.19.2)

#### Your filter lists (Required)
    
    uBlock filters
    uBlock filters – Badware risks​
    uBlock filters – Privacy​​​​​
    uBlock filters – Resource abuse​​​​​
    uBlock filters – Unbreak​​​​
    Adblock Warning Removal List​
    EasyList​
    AdGuard Tracking Protection
    EasyPrivacy​
    Malware Domain List​​​​​
    Malware domains​
    hpHosts’ Ad and tracking servers​​​​​
    Peter Lowe’s Ad and tracking server list
    spa, por: AdGuard Spanish/Portuguese
    Nano Defender Integration
    Nano Filters

**Comment by jspenguin2017** [comment] 2019-05-22 00:38
@okiehsch Seems to be hard anti-adblock. Thumbnails normally shows.

**Comment by jspenguin2017** [comment] 2019-05-22 01:21
Duplicate of https://github.com/NanoAdblocker/NanoFilters/issues/335

**Closed by jspenguin2017** 2019-05-22 01:21 UTC
Labels: confirmed
