### ISSUE TITLE
[Ads] ondemandkorea.com

### ISSUE THREAD

**Issue by beastbeats1** [NanoAdblocker/NanoFilters#342] opened 2019-05-27 21:41 UTC
### URLs where this issue occurs (Required)

https://www.ondemandkorea.com/documentary

### Screenshots (Required)
![ondemand](https://user-images.githubusercontent.com/51098224/58440078-abb16680-80a5-11e9-9b05-151f7f0fecbf.PNG)

### Screenshot of console (Required, press `F12` to open the console)
![ondemand2](https://user-images.githubusercontent.com/51098224/58440083-b10eb100-80a5-11e9-9b7d-b393f2fad5c7.PNG)

### Describe the issue (Optional if obvious)
nano adblocker does not block any of the ads in the player

#### Environment (Required)

- Operating System and Version: windows 7 home
- Browser and Version: Version 74.0.3729.169 (Official Build) (64-bit)
- Nano Adblocker Version: 1.0.0.112
- Nano Defender Version (Optional if you are not using it):  15.0.0.147

#### Your filter lists (Required)

101,105 network filters ＋ 47,512 cosmetic filters from:
 My filters​​​​​0 used out of 0​​​​
Built-in (7/11)
Nano filters​​​​​218 used out of 218​​​​
Nano filters – Whitelist​​​​​1 used out of 1​​​​
uBlock filters​​​​​16,585 used out of 16,612​​​​
uBlock filters – Badware risks​​​​​129 used out of 129​​​​
uBlock filters – Privacy​​​​​159 used out of 159​​​​
uBlock filters – Resource abuse​​​​​112 used out of 112​​​​
uBlock filters – Unbreak​​​​​942 used out of 945​​​​
Ads (2/5)
Adblock Warning Removal List​​​​​661 used out of 665​​​​
EasyList​​​​​92,853 used out of 93,136​​​​
Privacy (1/3)
EasyPrivacy​​​​​17,069 used out of 17,138​​​​
Malware domains (2/4)
Malware Domain List​​​​​1,105 used out of 1,105​​​​
Malware domains​​​​​26,884 used out of 26,899​​​​
Annoyances (0/6)
Multipurpose (1/4)
Peter Lowe's Ad and tracking server list​​​​​2,943 used out of 2,943​​​​

**Comment by jspenguin2017** [comment] 2019-05-28 00:51
@okiehsch Korean regional filters did not help. 
![image](https://user-images.githubusercontent.com/7283682/58443644-72cabf00-80b0-11e9-8993-0ae6ee32860b.png)

**Comment by jspenguin2017** [comment] 2019-05-28 00:53
Another test link (video ads): https://www.ondemandkorea.com/world-theme-travel-e2297.html

**Comment by okiehsch** [comment] 2019-05-28 00:54
https://github.com/NanoMeow/QuickReports/issues/1038#issuecomment-486553421

**Comment by jspenguin2017** [comment] 2019-05-28 00:55
Ops... Totally missed that. Sorry.

**Comment by jspenguin2017** [comment] 2019-05-28 00:55
Duplicate of https://github.com/NanoMeow/QuickReports/issues/1038

**Closed by jspenguin2017** 2019-05-28 00:55 UTC
Labels: confirmed
