### ISSUE TITLE
ADBLOCK DETECTED! You are running an ADBlock extension or ADBlock setting is enabled in your browser... ISSUE SOLVED!

### ISSUE THREAD

**Issue by paulsungte** [NanoAdblocker/NanoFilters#561] opened 2020-09-20 22:31 UTC
Just change the protocol from **"https://"**  _to_ **"http://"** and **reload** the page everytime the popup appears.. and you're good to go.
P.S. i don't have any adBlock installed and my settings are on "Allowed" on ads popups.
_SO.... the download can't work unfortunately._
but **found an alternate website** supposedly linked to mac-torrents.io where you can directly download the torrent files **http://mactorrent.co/torrents1.php?mode=details&id=66a141a74e0d13c08ab748a5728ad49dce8ca831**
![Screen Shot 2020-09-21 at 4 05 47 AM](https://user-images.githubusercontent.com/32662810/93723851-d7702e00-fbbf-11ea-9976-7169044fee7d.png)
![Screen Shot 2020-09-21 at 4 06 09 AM](https://user-images.githubusercontent.com/32662810/93723855-e22ac300-fbbf-11ea-8a99-1c76b3dc72a1.png)
![Screen Shot 2020-09-21 at 4 48 01 AM](https://user-images.githubusercontent.com/32662810/93724554-ac88d880-fbc5-11ea-9649-98ce21b2ec4a.png)

**Comment by jspenguin2017** [comment] 2020-09-21 14:50
Duplicate of https://github.com/NanoMeow/QuickReports/issues/2636

**Closed by jspenguin2017** 2020-09-21 14:50 UTC
