### ISSUE TITLE
[Ads] twitch.tv

### ISSUE THREAD

**Issue by dusty-dusty** [NanoAdblocker/NanoFilters#567] opened 2020-09-30 04:05 UTC
https://www.twitch.tv/ ads are now bypassing Adblock. Pre-roll ads and mid-roll ads of streamers  

[reports here of vast majority of people having the issue.](https://www.reddit.com/r/LivestreamFail/comments/j28ada/how_to_block_the_new_twitch_ads_with_ublock_origin/) 

[reports here of people using nano defender having the issue aswell](https://www.reddit.com/r/uBlockOrigin/comments/j2648i/how_to_kill_ads_on_twitch/)

**Comment by jspenguin2017** [comment] 2020-09-30 04:08
Duplicate of https://github.com/NanoMeow/QuickReports/issues/68

**Closed by jspenguin2017** 2020-09-30 04:08 UTC
Labels: duplicate
