### ISSUE TITLE
[Anti-adblock] duellinksmeta.com

### ISSUE THREAD

**Issue by rain727** [NanoAdblocker/NanoFilters#225] opened 2018-12-01 04:58 UTC
### www.duellinksmeta.com

###![adblockdetect](https://user-images.githubusercontent.com/45505074/49324367-ee242d00-f4e0-11e8-91c4-c1bb22701193.png)

###![console1](https://user-images.githubusercontent.com/45505074/49324371-02682a00-f4e1-11e8-9505-e5113928ebfe.png)

###When I try to browse this website to see yugioh card decks for duel links, it prevents me from using the site unless I turn off Nano Adblocker, I have nano defender too but it doesn't seem to work on this site

#### Environment (Required)

- Operating System and Version: Windows 10 home 
- Browser and Version: Chrome Version 70.0.3538.110 (Official Build) (64-bit)
- Nano Adblocker Version: Version
1.0.0.78
- Nano Defender Version (Optional if you are not using it): Version
15.0.0.79

#### 
![filters](https://user-images.githubusercontent.com/45505074/49324443-8cfd5900-f4e2-11e8-9d8f-6170228c756f.png)

#### Your custom filters (Required if you have any)

I haven't added anything

**Comment by jspenguin2017** [comment] 2018-12-01 05:14
@okiehsch Takes ~3 navigations.

**Comment by jspenguin2017** [comment] 2018-12-01 06:03
Duplicate of https://github.com/NanoMeow/QuickReports/issues/391

**Closed by jspenguin2017** 2018-12-01 06:03 UTC
Labels: confirmed

**Comment by okiehsch** [comment] 2018-12-01 06:37
Fixed https://github.com/uBlockOrigin/uAssets/commit/65e73c3b52cbb12ebb069709d0acae7c1d6b12fa
