### ISSUE TITLE
[Anti-adblock] washingtonpost.com

### ISSUE THREAD

**Issue by BlohoJo** [NanoAdblocker/NanoFilters#401] opened 2019-09-20 16:02 UTC
### URLs where this issue occurs (Required)

https://www.washingtonpost.com/nation/2019/09/17/police-say-she-abandoned-her-adopted-daughter-she-says-girl-was-actually-scamming-adult-sociopath/

### Screenshots (Required)

![wp](https://user-images.githubusercontent.com/8242464/65340333-ff3b4900-db9b-11e9-99c4-ada0da36f606.png)

### Screenshot of console (Required, press `F12` to open the console)

![console1](https://user-images.githubusercontent.com/8242464/65340826-13337a80-db9d-11e9-86cb-ed212843b6da.png)
![console2](https://user-images.githubusercontent.com/8242464/65340827-13337a80-db9d-11e9-8579-77c16413dedd.png)
![console3](https://user-images.githubusercontent.com/8242464/65340828-13337a80-db9d-11e9-9354-c0d91573c2d3.png)

### Anything else you believe to be useful (Optional)

Was working OK at least a few days ago.

#### Environment (Required)

- Operating System and Version: Windows Server 2008 R2
- Browser and Version: Chromium Version 70.0.3538.77 (Official Build) (64-bit)
- Nano Adblocker Version: 15.0.0.168
- Nano Defender Version (Not using, using uBlock): uBlock Origin 1.22.2

#### Your filter lists (Required)

uBlock filters​​​​​
uBlock filters – Annoyances
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse
uBlock filters – Unbreak​​​​​
Adblock Warning Removal List
EasyList​​​​​​​​​​
EasyPrivacy​​​​​
Malware Domain List​​​​​
Malware domains
Peter Lowe’s Ad and tracking server list
Nano Defender Integration
Nano Filters
Nano Filters - Whitelist

#### Your other extensions (Required if you have any)

![exten1](https://user-images.githubusercontent.com/8242464/65341429-5b9f6800-db9e-11e9-876f-09e81d0d1efb.png)
![exten2](https://user-images.githubusercontent.com/8242464/65341430-5b9f6800-db9e-11e9-806a-490ae44c34ee.png)

**Comment by jspenguin2017** [comment] 2019-09-20 16:35
Duplicate of https://github.com/NanoMeow/QuickReports/issues/1499

**Closed** 2019-09-20 16:34 UTC
