### ISSUE TITLE
[Anti-adblock] spiegel.de

### ISSUE THREAD

**Issue by sangiisaurus** [NanoAdblocker/NanoFilters#455] opened 2020-02-11 12:57 UTC
### URLs where this issue occurs (Required)
https://www.spiegel.de/consent-a-?targetUrl=https%3A%2F%2Fwww.spiegel.de%2F

### Screenshots (Required)

![image](https://user-images.githubusercontent.com/60926776/74238323-db58db00-4cd5-11ea-862d-cfd28b6c0a52.png)

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/60926776/74238390-fa576d00-4cd5-11ea-954b-ec05f2882d7a.png)

### Describe the issue (Optional if obvious)
Its blocked due to adblockers.

#### Environment (Required)

- Operating System and Version: 
- Browser and Version: Version 80.0.3987.87 (Offizieller Build) beta (64-Bit)
- Nano Adblocker Version: 1.0.0.135
- Nano Defender Version (Optional if you are not using it): 15.0.0.85

#### Your filter lists (Required)

![image](https://user-images.githubusercontent.com/60926776/74238538-4c988e00-4cd6-11ea-9635-ee635f19234e.png)

#### Your custom filters (Required if you have any)
None

#### Your other extensions (Required if you have any)

None

**Comment by mapx-** [comment] 2020-02-11 14:29
test
`spiegel.de#@#+js(aopr, _sp_.mms.startMsg)`

if you could test in FF too (it seems to work for chrome but not for FF)

**Comment by mapx-** [comment] 2020-02-11 15:54
for FF it seems necessary this 1 too
`@@||sp-prod.net^$script,domain=spiegel.de`

**Comment by sangiisaurus** [comment] 2020-02-11 19:02
> for FF it seems necessary this 1 too
> `@@||sp-prod.net^$script,domain=spiegel.de`

where do i enter this? in my filterlist? console? actualy new to this. i did it for both and it doesnt work :(

**Comment by mapx-** [comment] 2020-02-11 19:17
First update the filter lists (uBo filters list), test again, if still does not work add the second filter in "my filters"  (options, dashboard, "my filters" tab, click apply changes)

However, first clear the cookies, then test the page and click spiegel's ACCEPT. Then it should work.

**Comment by jspenguin2017** [comment] 2020-02-11 21:49
Duplicate of https://github.com/NanoMeow/QuickReports/issues/598

**Closed by jspenguin2017** 2020-02-11 21:49 UTC
Labels: duplicate

**Comment by therealmarv** [comment] 2020-02-12 16:24
EasyList Cookie is conflicting with this (needs to be temporarily deactivated).

**Comment by mapx-** [comment] 2020-02-12 16:37
temporarily fixed in unbreak list, @ryanbr
