### ISSUE TITLE
[Anti-adblock] mail.yahoo.com

### ISSUE THREAD

**Issue by whitecoatblackhat** [NanoAdblocker/NanoFilters#501] opened 2020-05-18 11:34 UTC
### Screenshots (Required)

![Yahoo Adblock Detection](https://user-images.githubusercontent.com/65068012/82208187-ff464100-9902-11ea-9b34-356b4f034291.PNG)

### Reproduction Steps (Optional if trivial)

UOrigins + Nano Defender used to bypass Yahoo Mail's anti-adblock system but it no longer can. 

#### Environment (Required)

- Operating System and Version: Windows 10 Home x64
- Browser and Version: Chrome Version 81.0.4044.138 (Official Build) (64-bit)
- Nano Adblocker Version: UOrigins 1.26.0
- Nano Defender Version (Optional if you are not using it): 15.0.0.198

**Comment by mapx-** [comment] 2020-05-18 11:58
test this filter
`mail.yahoo.com##:xpath(//*[contains(text(),"ad-blocker")]):upward(3)`

**Comment by jspenguin2017** [comment] 2020-05-18 14:42
Duplicate of https://github.com/NanoMeow/QuickReports/issues/3789

**Comment by whitecoatblackhat** [comment] 2020-05-19 12:55
Ahh, got it! Many thanks!!

**Closed** 2020-05-19 14:45 UTC
Labels: fixed
