### ISSUE TITLE
[Anti-adblock] linetv.tw

### ISSUE THREAD

**Issue by lancelot-moon** [NanoAdblocker/NanoFilters#287] opened 2019-03-19 01:09 UTC
Describe the issue (Required)
Can't play Line TV's videos when Nano Adblocker is on.

Screenshots (Required)
When Nano Adblocker is on:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/qOMT6dl.png)
</details><br/>

URLs where this issue occurs (Required if applicable)
https://www.linetv.tw/drama/10052/eps/1

Reproduction Steps (Optional if trivial)
When Nano Adblocker is on, it's black screen.

Anything else you believe to be useful (Optional)

Environment (Required)
Operating System and Version: Windows 10
Browser and Version: Chrome v73.0.3683.75 (Official Build) (64-bit)
Nano Adblocker Version: Nano Adblocker v1.0.0.96
Nano Defender Version (Optional if you are not using it): 15.0.0.109

Your filter lists (Required)
Default filters in the "built-in" section.

Your custom filters (Required if you have any)

**Comment by lancelot-moon** [comment] 2019-03-19 01:16
Need to unblock `www.google-analytics.com/analytics.js`.
Please add `@@||www.google-analytics.com/analytics.js^$domain=linetv.tw`.

**Comment by jspenguin2017** [comment] 2019-03-19 03:42
@okiehsch Tried regional filters.

**Comment by okiehsch** [comment] 2019-03-19 04:00
`@@||google-analytics.com/analytics.js$script,domain=linetv.tw`
but I get this message
````
此部戲劇已下架，如有不便請見諒
回首頁
````
which apparently means that the video has been removed or something to that effect I tried different links but all produced the same message on my end.

**Comment by lancelot-moon** [comment] 2019-03-19 04:12
No, I just tried it this morning.
Otherwise, there are so many videos on Line TV.
You can try any one.

**Comment by okiehsch** [comment] 2019-03-19 04:18
Well I tried a few and get the same message, anyway I added 
`@@||google-analytics.com/analytics.js$script,domain=linetv.tw`
to `uBO-unbreak`, so if you update that list and don't get the message the issue should be fixed for you.

**Comment by jspenguin2017** [comment] 2019-03-19 12:47
Could be GeoLock.

**Comment by lancelot-moon** [comment] 2019-04-04 13:33
@jspenguin2017
@okiehsch 

2 days ago, Line TV website may update scripts.
If enabling **EasyList filter** in Nano Adblocker, it'll show the warning:
**Currently, disagree the video to be played in your region, please forgive if it's inconvenient.
Back to Homepage**
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/YQgsLAw.png)
</details><br/>

**As long as disable EasyList filter, no the warning.**

Please fix it.
Thanks.

**Comment by jspenguin2017** [comment] 2019-04-06 04:56
For some reason I can't get past the GeoLock even with a VPN...

**Comment by okiehsch** [comment] 2019-04-06 05:29
Me too but
`https://web-static.linetv.tw/public/scripts/ads.js`
looks promising.
@lancelot-moon does it work if  you allow that request?
`@@||web-static.linetv.tw/public/scripts/ads.js$script,1p`

**Comment by lancelot-moon** [comment] 2019-04-06 06:12
@jspenguin2017 

No, it's actually not GeoLock.
I live in Taiwan.
I even can't watch video with EasyList filter enabled in Nano.
Line TV website updated scripts recently.

@okiehsch 
No, `@@||web-static.linetv.tw/public/scripts/ads.js$script,1p` is **invalid** for me.
I tried to whitelist it.
I still can't normally watch video.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/7hegdx1.png)
</details><br/>

I requested AdGuard to add new rules in AdGuard Base filter, which can solve the issue.
I suppose that maybe you can make other rules.
https://github.com/AdguardTeam/AdguardFilters/issues/26883#issuecomment-479868911

**Comment by jspenguin2017** [comment] 2019-04-06 06:15
It's certainly GeoLock for me. 
![image](https://user-images.githubusercontent.com/7283682/55665655-01356980-5801-11e9-9015-b67103718995.png)

**Comment by lancelot-moon** [comment] 2019-04-06 06:16
I mean you'll meet the GeoLock warning even if you use Taiwanese IP.

**Comment by jspenguin2017** [comment] 2019-04-06 06:20
I don't have any extensions enabled beside Hola.

**Comment by lancelot-moon** [comment] 2019-04-06 06:22
@jspenguin2017 

Maybe Line TV detects and refuses VPN IP.
I don't know.
Only guess.

Try to enable AdGuard Base filter in Nano and use Taiwanese IP.
Can you can normally watch video?

**Comment by jspenguin2017** [comment] 2019-04-06 06:24
I don't have a way to use Taiwanese IP.

**Comment by lancelot-moon** [comment] 2019-04-06 06:26
You used Hola VPN for Taiwanese IP, right?
BTW Hola VPN isn't safe...

Well, first need Taiwanese IP for the test.

**Comment by jspenguin2017** [comment] 2019-04-06 06:30
For some reason Hola doesn't work. 
Also I don't need it to be safe, I'm just testing filters.

**Comment by lancelot-moon** [comment] 2019-04-06 06:40
After enabling & updating AdGuard Base filter in Nano with EasyList filter, videos can be played.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/YmMSauJ.jpg)
</details><br/>

You can add rules into `uBO-unbreak` filter.

**Comment by lancelot-moon** [comment] 2019-04-06 07:04
@okiehsch
Unticking `@@||linetv.tw/public/scripts/ads.js` in EasyList China filter of AG for Windows can solve the issue without my 2 rules, too.

I'm not sure if you have `@@||linetv.tw/public/scripts/ads.js` in EasyList filter of Nano.
Maybe you can delete `@@||linetv.tw/public/scripts/ads.js` from EasyList filter aand try.

**Comment by okiehsch** [comment] 2019-04-06 07:44
`@@||linetv.tw/public/scripts/ads.js` is not part of `EasyLIst`.
If `@@||linetv.tw/public/scripts/ads.js$badfilter` works on your end I can add it to `uBO-filters`

**Comment by lancelot-moon** [comment] 2019-04-06 08:47
No, `@@||linetv.tw/public/scripts/ads.js$badfilter` is invalid.

In uBO or AdGuard, only enabling one of Base filter, EasyList filter and EasyList China filter won't cause the warning.
But enabling EasyList filter + EasyList China filter or previous AdGuard Base filter (without my 2 new rules) + EasyList China filter causes the warning.

With Nano, only enabling EasyList filter without EasyList China filter in Nano will cause the warning.

**Comment by lancelot-moon** [comment] 2019-04-06 09:04
@okiehsch 

Finally, I found **Nano Defender v15.0.0.121 + EasyList filter** cause the warning.
Only enabling EasyList filter in Nano Adblocker but disabling Nano Defender won't cause the warning.

**Comment by lancelot-moon** [comment] 2019-04-06 10:07
@okiehsch

1. You can add `@@||linetv.tw/public/scripts/ads.js$badfilter` into uBO filter for users who enable EasyList China filter and don't use Nano Defender.

2. Nano Defender v15.0.0.121 + EasyList filter will cause the warning.
Can you find any causes in Nano Defender?

**Comment by jspenguin2017** [comment] 2019-04-06 16:49
I can't test but I whitelisted it in Nano Defender.

**Comment by lancelot-moon** [comment] 2019-04-06 22:11
@okiehsch

Please add `@@||linetv.tw/public/scripts/ads.js$badfilter` into uBO filter for users who enable EasyList filter + EasyList China filter.

@jspenguin2017 had whitelisted linetv.tw in Nano Defender.
It has been no problem with Nano Defender.
(With my 2 rules in AdGuard Base filter, don't need to whitelisted linetv.tw in Nano Defender.)

**Comment by okiehsch** [comment] 2019-04-06 22:17
Added to `uBO-unbreak`.

**Comment by lancelot-moon** [comment] 2019-04-06 22:24
@okiehsch
If only enabling AdGuard Mobile Ads filter without AdGuard Base filter, EasyList filter and EasyList China filter, it will still show the GeoLock warning.

Need to also add `@@||imasdk.googleapis.com/js/sdkloader/ima3.js^$domain=linetv.tw`

**Comment by okiehsch** [comment] 2019-04-06 22:39
Filters will only be added if the issue occurs with a default setup, for a chinese site this is the default setup.
![image](https://user-images.githubusercontent.com/16838044/55676076-86865000-58cd-11e9-8a53-5a353fe78854.png)

Do you have any issues if you use these lists?

**Comment by lancelot-moon** [comment] 2019-04-06 22:46
No, I won't have any issues if using the above lists since you had added a rule, and Nano Defender whitelisted linetv.tw.

I only report.
AdGuard Mobile Ads filter has the rule `||imasdk.googleapis.com^` but doesn't have `/videojs.ads.`.
imasdk.googleapis.com/js/sdkloader/ima3.js will be blocked by `||imasdk.googleapis.com^`.
Without `/videojs.ads.`, cdnjs.cloudflare.com/ajax/libs/videojs-contrib-ads/*/videojs.ads.min.js will be allowed.
That will cause the GeoLock warning, too.

**Comment by okiehsch** [comment] 2019-04-06 22:53
Well, report it at `https://github.com/AdguardTeam/AdguardFilters` I can't start adding filters to `uAssets` to 
fix issues caused by `AdGuard Mobile Ads`.

**Comment by okiehsch** [comment] 2019-04-06 23:02
Actually that list is enabled by default if one uses a mobile device.
I will add
````
!#if env_mobile
@@||imasdk.googleapis.com/js/sdkloader/ima3.js^$domain=linetv.tw
!#endif

**Comment by lancelot-moon** [comment] 2019-04-06 23:08
Well, you got it.
Someone may use FireFox for Android with uBO/Nano.
If only enabling AdGuard Mobile Ads filter without EasyList filter, only `@@||linetv.tw/public/scripts/ads.js$badfilter` isn't enough.
Need `@@||imasdk.googleapis.com/js/sdkloader/ima3.js^$domain=linetv.tw` at least.
Please add that code.

**Comment by lancelot-moon** [comment] 2019-04-07 00:44
@okiehsch 
`||google-analytics.com/analytics.js$important,script` in uBlock filters – Experimental​​​​​​​​​ will cause black screen such like the screenshot.
Is it possible to delete it?
Or simply don't use uBlock filters – Experimental​​​​​​​​​.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/qOMT6dl.png)
</details><br/>

**Comment by lancelot-moon** [comment] 2019-04-07 01:11
@okiehsch 

Is it a bug that the priority of `||google-analytics.com/analytics.js$script,redirect=google-analytics.com/analytics.js,important` is higher than `@@||www.google-analytics.com/analytics.js^$domain=linetv.tw`?

**Comment by okiehsch** [comment] 2019-04-07 02:05
> Or simply don't use uBlock filters – Experimental​​​​​​​​​?

Don't use it, it will probably be removed anyway.

**Comment by lancelot-moon** [comment] 2019-04-10 01:26
@okiehsch

**EasyList filter + Fanboy's Enhanced Tracking List** will also cause the GeoLock warning.

`@@/scripts/ads.js$script` in Fanboy's Enhanced Tracking List will unlock `web-static.linetv.tw/public/scripts/ads.js?v=9.8.0`.
`@@||linetv.tw/public/scripts/ads.js$badfilter` can't work for  `@@/scripts/ads.js$script`.

BTW, I had notified EasyList China filter to delete `@@||linetv.tw/public/scripts/ads.js`.
EasyList China filter also added my 2 rules in its filter.
`@@||imasdk.googleapis.com/js/sdkloader/ima3.js^$domain=linetv.tw`
`@@||cdnjs.cloudflare.com/ajax/libs/videojs-contrib-ads/*/videojs.ads.min.js^$domain=linetv.tw`

**Closed** 2019-04-12 03:10 UTC
Labels: backlog, detects VPN, geolock
