### ISSUE TITLE
[Anti-adblock] egy.best

### ISSUE THREAD

**Issue by get50** [NanoAdblocker/NanoFilters#375] opened 2019-07-20 19:54 UTC
https://www.egy.best/movie/aladdin-2019/?ref=home-trends

### Screenshots (Required)
![Untitled](https://user-images.githubusercontent.com/15727090/61583545-d36afb00-ab39-11e9-91dc-d06aefa7b2c2.png)

### Screenshot of console (Required, press `F12` to open the console)
![Untitled](https://user-images.githubusercontent.com/15727090/61583555-04e3c680-ab3a-11e9-8f4b-cd7f46a2331a.png)

#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by llacb47** [comment] 2019-07-20 20:09
Update your filters and try again.

**Comment by llacb47** [comment] 2019-07-20 20:11
Ugh. I'm getting anti-adblock on `egy.best` too.

**Comment by jspenguin2017** [comment] 2019-07-20 20:33
Can't reproduce.

**Comment by krystian3w** [comment] 2019-07-20 22:38
Also have, no help use restored filters or from:

#373

**Comment by jspenguin2017** [comment] 2019-07-20 23:28
Duplicate of https://github.com/NanoAdblocker/NanoFilters/issues/376

**Closed by jspenguin2017** 2019-07-20 23:28 UTC
Labels: cannot reproduce
