### ISSUE TITLE
[Anti-adblock] dplay.se

### ISSUE THREAD

**Issue by stanlane** [NanoAdblocker/NanoFilters#299] opened 2019-04-06 02:13 UTC
### URLs where this issue occurs (Required)
https://www.dplay.se/videos/sommaren-med-slakten/sommaren-med-slakten-29

All videos on [dplay.se](https://www.dplay.se/)

### Screenshots (Required)
![Screenshot at 2019-04-06 03:21:37](https://user-images.githubusercontent.com/25944158/55663709-3ef6ba00-5822-11e9-8a0a-e304a291676b.png)

### Screenshot of console (Required, press `F12` to open the console)

> [Nano] Nano Defender Activated :: github.com
> core.js:12:5
> Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: (() => {
>     "use strict";
> 	window.nanoC....
> 299:1
> Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: (() => {
>         "use strict";
>         c....
> 299:1
> Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: (() => {
>         "use strict";
> 
>         ....
> 299:1
> Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: (() => {
>         "use strict";
>         c....
> 299:1
> Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: (() => {
>         try {
>             // co....
> 299:1
> Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: (() => {
>         "use strict";
>         t....
> 299:1
> Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: (() => {
>                     "use strict....
> 299:1
> This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!

### Describe the issue (Optional if obvious)
Doesn't work with [Privacy Badger](https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/?src=search) installed.

#### Environment (Required)

- Operating System and Version: GNU/Linux
- Browser and Version: Firefox 60.6.1
- Nano Adblocker Version: uBlock Origin 1.18.16
- Nano Defender Version (Optional if you are not using it): 15.0.0.121

#### Your filter lists (Required)

https://jspenguin2017.github.io/uBlockProtector/#extra-installation-steps-for-ublock-origin

#### Your custom filters (Required if you have any)
Swedish regional filter enabled.

**Comment by jspenguin2017** [comment] 2019-04-06 04:57
It works fine with Swedish regional filters enabled. 
![image](https://user-images.githubusercontent.com/7283682/55665080-38eae400-57f6-11e9-86d7-34ae51f50d1e.png)

**Comment by stanlane** [comment] 2019-04-06 06:16
> It works fine with Swedish regional filters enabled.
> ![image](https://user-images.githubusercontent.com/7283682/55665080-38eae400-57f6-11e9-86d7-34ae51f50d1e.png)

Thanks for the report. I forgot to mention that the Swedish regional filter was enabled in my configured settings.

**Comment by jspenguin2017** [comment] 2019-04-06 06:18
I can't reproduce. 
Try disabling Privacy Badger.

**Comment by stanlane** [comment] 2019-04-06 18:17
Yes it's working with Privacy Badger disabled. Is it possible for Nano Defender to interact with Privacy Badger so I can keep it enabled?

**Comment by jspenguin2017** [comment] 2019-04-06 18:21
That's out of scope.

**Closed by jspenguin2017** 2019-04-06 18:21 UTC
Labels: cannot reproduce

**Comment by stanlane** [comment] 2019-04-06 19:01
https://github.com/EFForg/privacybadger/issues/2346
