### ISSUE TITLE
[Ads] twitch.tv

### ISSUE THREAD

**Issue by gfmate123** [NanoAdblocker/NanoFilters#182] opened 2018-09-14 05:27 UTC
### Screenshots (Required)
i am getting ads on broadcasters i use nano adblocker and nano defender

### Screenshot of console (Required, press `F12` to open the console)

![image](https://user-images.githubusercontent.com/16946412/45531282-10998a80-b7bd-11e8-84f4-3f8de6570603.png)

### Describe the issue (Optional if obvious)
i am getting ads on broadcasters i use nano adblocker and nano defender

#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by jspenguin2017** [comment] 2018-09-14 12:33
Duplicate of https://github.com/NanoMeow/QuickReports/issues/68

**Closed** 2018-09-14 12:32 UTC
Labels: duplicate
