### ISSUE TITLE
[Anti-adblock] aternos.org

### ISSUE THREAD

**Issue by hyperak** [NanoAdblocker/NanoFilters#450] opened 2020-02-02 03:30 UTC
### URLs where this issue occurs (Required)

https://aternos.org/

### Screenshots (Required)

![image](https://user-images.githubusercontent.com/29081800/73602435-4f62e880-454a-11ea-86c2-e1a7e1b01a30.png)

### Screenshot of console (Required, press `F12` to open the console)

![image](https://user-images.githubusercontent.com/29081800/73602439-643f7c00-454a-11ea-8ee7-2d7eea50a715.png)

### Describe the issue (Optional if obvious)

Every time a page loads in this website, this nagging message covers the entire screen. If you press the proceed button, **you need to wait 3 seconds for it to disappear.**

### Reproduction Steps (Optional if trivial)

I believe this only happens in the dashboard.

#### Environment (Required)

- Operating System and Version: Arch Linux 5.4.12 
- Browser and Version: Firefox 72.0.1 64bit
- Nano Adblocker Version: 1.0.0.134
- Nano Defender Version (Optional if you are not using it): 15.0.0.182

#### Your filter lists (Required)

![image](https://user-images.githubusercontent.com/29081800/73602474-c4362280-454a-11ea-945a-f55a2c6cf7bb.png)

**Comment by jspenguin2017** [comment] 2020-02-02 05:22
Duplicate of https://github.com/NanoMeow/QuickReports/issues/1643

**Closed by jspenguin2017** 2020-02-02 05:22 UTC
Labels: duplicate
