### ISSUE TITLE
dallasnews.com

### ISSUE THREAD

**Issue by nanorocks1** [NanoAdblocker/NanoFilters#95] opened 2018-06-05 20:16 UTC
https://www.dallasnews.com/news/politics/2018/06/05/trumps-claim-absolute-right-pardon-ted-cruz-noncommittal-republicans-balk

When I visit the site, it detects an adblocker.

Windows 7 Enterprise Service Pack 1
Chrome Version 66.0.3359.181
uBlock Origin with Nano Defender
Nano Defender V 14.45
Auto-update filter lists 
Parse and enforce cosmetic filters
Ignore generic cosmetic filters
84,234 network filters ＋ 45,757 cosmetic filters from:
 My filters​​​​​0 used out of 0​​​​
Built-in (5/7)
uBlock filters​​​​​6,081 used out of 6,082​​​​
uBlock filters – Badware risks​​​​​11 used out of 11​​​​
uBlock filters – Privacy​​​​​96 used out of 97​​​​
uBlock filters – Resource abuse​​​​​260 used out of 262​​​​
uBlock filters – Unbreak​​​​​446 used out of 446​​​​
Ads (2/4)
Adblock Warning Removal List​​​​​440 used out of 446​​​​
EasyList​​​​​82,424 used out of 82,569​​​​
Privacy (1/3)
EasyPrivacy​​​​​14,914 used out of 15,093​​​​
Malware domains (2/4)
Malware Domain List​​​​​1,116 used out of 1,131​​​​
Malware domains​​​​​22,549 used out of 22,549​​​​
Annoyances (0/5)
Multipurpose (1/4)
Peter Lowe’s Ad and tracking server list​​​​​2,630 used out of 2,634​​​​
Regions, languages (0/36)
Custom (6/6)
https://jspenguin.com/NanoAdblocker/AssetsMirror/NanoBase.txt​​​​​89 used out of 90​​​​
https://jspenguin.com/NanoAdblocker/AssetsMirror/NanoDefender.txt​​​​​0 used out of 2,749​​​​
https://jspenguin.com/NanoAdblocker/AssetsMirror/NanoWhitelist.txt​​​​​0 used out of 0​​​​
AAK-Cont Filter For uBlock Origin​​​​​48 used out of 2,785​​​​
Ebates Cash Back Shopping​​​​​216 used out of 219​​​​
uBlock Protector List​​​​​2,640 used out of 2,749​​​​
Import...
[Doc1.docx](https://github.com/NanoAdblocker/NanoFilters/files/2073844/Doc1.docx)

#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by jspenguin2017** [comment] 2018-06-06 00:00
Can't reproduce. Closing as invalid because you did not fill the template. 
![image](https://user-images.githubusercontent.com/7283682/41008777-28d79f5a-68ea-11e8-8f57-6131645e9537.png)

**Closed by jspenguin2017** 2018-06-06 00:00 UTC
Labels: invalid

**Comment by nanorocks1** [comment] 2018-06-06 00:34
What do you mean I did not fill the template. I looked at all the
instructions on how to report and put in everything including screen
captures of the glitch and dashboard so I am confused with your statement.

**Comment by jspenguin2017** [comment] 2018-06-06 01:00
Why did you attach a DOCX file instead of properly pasting a screenshot? Also fill the actual template, don't dump everything in a wall of text. 

Anyway, I still can't reproduce this issue.

**Comment by nanorocks1** [comment] 2018-06-06 02:58
Ok sorry about that. I will check again tomorrow.

**Comment by nanorocks1** [comment] 2018-06-06 16:58
Hi Hugo,

I checked the website again and can reproduce the issue. Should I put in a
NEW ISSUE entry the correct way as you told me or should I not bother.
Thank you.

Ryan

**Comment by jspenguin2017** [comment] 2018-06-07 00:04
I still can't reproduce.
