### ISSUE TITLE
[Ads] controlc.com

### ISSUE THREAD

**Issue by Cyberavater** [NanoAdblocker/NanoFilters#454] opened 2020-02-10 15:31 UTC
Split from #368 & #441

It seems they are re-appearing. This time more annoying than before.

Eg link; https://controlc.com/a19e8e3d

**Comment by jspenguin2017** [comment] 2020-02-11 21:37
Can't reproduce. Closing as invalid as you did not fill the template.

**Closed by jspenguin2017** 2020-02-11 21:37 UTC
Labels: invalid

**Comment by Cyberavater** [comment] 2020-02-12 04:31
It seems it's gone again now. Maybe comes goes and comes back from time to time.

**Comment by jspenguin2017** [comment] 2020-02-12 04:33
OK, open a new issue with proper details if it comes back.
