### ISSUE TITLE
[Anti-adblock] cola.egybest.com

### ISSUE THREAD

**Issue by YASINEDr** [NanoAdblocker/NanoFilters#396] opened 2019-08-31 00:05 UTC
### URLs where this issue occurs (Required)

https://cola.egybest.com/

### Screenshots (Required)

![screenshot-cola egybest com-2019 08 31-01_04_30](https://user-images.githubusercontent.com/34688076/64056475-56e12880-cb8b-11e9-9d25-e0971e7b8114.png)

#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by jspenguin2017** [comment] 2019-08-31 00:10
Duplicate of https://github.com/NanoAdblocker/NanoFilters/issues/376

**Closed by jspenguin2017** 2019-08-31 00:10 UTC
