### ISSUE TITLE
[Anti-adblock] cbssports.com

### ISSUE THREAD

**Issue by beavislol** [NanoAdblocker/NanoFilters#556] opened 2020-09-07 22:53 UTC
#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by llacb47** [comment] 2020-09-07 23:00
https://github.com/uBlockOrigin/uAssets/issues/7866

**Comment by jspenguin2017** [comment] 2020-09-08 23:02
Can't reproduce. Closing as invalid since you did not fill the template.

**Closed by jspenguin2017** 2020-09-08 23:02 UTC
Labels: invalid

**Comment by krystian3w** [comment] 2020-09-09 07:01
https://github.com/NanoAdblocker/NanoFilters/issues/556
