### ISSUE TITLE
[Anti-adblock] 10play.com.au

### ISSUE THREAD

**Issue by Poopooracoocoo** [NanoAdblocker/NanoFilters#408] opened 2019-10-08 01:24 UTC
### URLs where this issue occurs (Required)

https://10play.com.au/theproject

### Screenshots (Required)
![image](https://user-images.githubusercontent.com/51363864/66359844-575bb300-e9c4-11e9-98e8-e037a75bcd1f.png)

### Screenshot of console (Required, press `F12` to open the console)
![console1](https://user-images.githubusercontent.com/51363864/66360108-89214980-e9c5-11e9-81ca-7250f87f205c.jpg)
![console2](https://user-images.githubusercontent.com/51363864/66360110-89b9e000-e9c5-11e9-92ef-dc6444304606.jpg)
![console3](https://user-images.githubusercontent.com/51363864/66360111-89b9e000-e9c5-11e9-8fb6-7735be1e4889.jpg)

### Reproduction Steps (Optional if trivial)

Navigate to the link without 10play having kept anything as if you click on continue 10play will remember it.

#### Environment (Required)

- Operating System and Version: Windows 10 1903 build 18362.388
- Browser and Version: I found this issue on Chrome stable (which is 77 IIRC) but this screenshot is from Chrome Canary version 79.0.3975.0
- Nano Adblocker Version: uBlock Origin v1.22.4
- Nano Defender Version (Optional if you are not using it): 15.0.0.168

#### Your filter lists (Required)

I haven't enabled or disabled anything. I've only followed the instructions on Nano Defender integration with uBO.

#### Your other extensions (Required if you have any)
picture in picture by google
tab muter by josh holland
iridium for youtube
goodtwitter
view image by joshua b

**Comment by jspenguin2017** [comment] 2019-10-08 01:38
Duplicate of https://github.com/NanoMeow/QuickReports/issues/1992

**Closed by jspenguin2017** 2019-10-08 01:38 UTC
Labels: duplicate

**Comment by Poopooracoocoo** [comment] 2019-10-08 03:34
@jspenguin2017 do the screenshot and extra details help?

**Comment by mapx-** [comment] 2019-10-08 06:18
@Poopooracoocoo did you test the filters here ?
https://github.com/NanoMeow/QuickReports/issues/1992#issuecomment-538775232

**Comment by jspenguin2017** [comment] 2019-10-09 01:53
@Poopooracoocoo Not for this case. This was already reproduced.
