### ISSUE TITLE
[Anti-adblock] strims.world

### ISSUE THREAD

**Issue by Majkovsky** [NanoAdblocker/NanoFilters#437] opened 2019-12-21 13:16 UTC
http://strims.world/SkokiKwalifikacje.php?source=1

**"BRAK PLAYERA? WYŁĄCZ ADBLOCKA!"**

Nano Defender **15.0.0.170**
Mozilla Firefox **71.0**

**Comment by jspenguin2017** [comment] 2019-12-21 18:59
Can't reproduce. Closing as invalid as you did not fill the template. 
![image](https://user-images.githubusercontent.com/7283682/71312530-46c6b080-23e9-11ea-8f5d-b3040ca94ea5.png)

**Closed by jspenguin2017** 2019-12-21 18:59 UTC
Labels: invalid

**Comment by krystian3w** [comment] 2019-12-21 22:55
https://github.com/LiCybora/NanoDefenderFirefox/issues/new
