### ISSUE TITLE
[Ads] twitch.tv

### ISSUE THREAD

**Issue by gfmate123** [NanoAdblocker/NanoFilters#569] opened 2020-10-06 03:32 UTC
### Describe the issue (Required)
any video i watch on twitch i get ads? i use nanoadblocker and defender

#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by jspenguin2017** [comment] 2020-10-06 03:53
Duplicate of https://github.com/NanoMeow/QuickReports/issues/68

**Closed by jspenguin2017** 2020-10-06 03:53 UTC
Labels: duplicate
