### ISSUE TITLE
[Anti-adblock, Popup] abysstream.com, 4snip.pw

### ISSUE THREAD

**Issue by Hadden89** [NanoAdblocker/NanoFilters#109] opened 2018-06-20 17:58 UTC
Sample [link](http://swzz.xyz/HR/go.php?id=52435). (with redirect)
Direct [link](http://abysstream.com/v/advzei4044kp) to video.

If the adblocker is detected, the countdown (10s) will loop and reload the page.
Sometimes even after the video is shown.

**Comment by jspenguin2017** [comment] 2018-06-21 00:34
Looks like the link is generated each time, so the direct link doesn't work. 
I can't reproduce page reload. 

@okiehsch There is a popup.

**Comment by okiehsch** [comment] 2018-06-21 00:57
I am not sure we get the same results, so to be clear on my end `http://swzz.xyz/HR/go.php?id=52435`
has no issues, if I then click "Clicca ..." I go to `http://abysstream.com/v/oo61xead49m3` which has an anti-adblock message and a timer which can be fixed by
````
@@||abysstream.com/ads.js$script,first-party
abysstream.com##script:inject(nano-setInterval-booster.js)
````
I do not get any popups.

**Comment by jspenguin2017** [comment] 2018-06-21 00:59
Hum, for the first time, it `swzz.xyz` sent me to an URL-shortening-like website which has popup, I can't reproduce anymore... Let me check my history.

**Comment by jspenguin2017** [comment] 2018-06-21 00:59
Can you test this link for popup? 
````
https://4snip.pw/out/zAeFM_ppl_L3W7lwjt5mY5xWLvgEqI9HXzfSSiZy7LRHAqfc1aqbChHvjf4nhSlX4F3D
```

**Comment by okiehsch** [comment] 2018-06-21 01:05
I get a popup, fixed by 
````
4snip.pw##script:inject(window.open-defuser.js)`
````

**Comment by jspenguin2017** [comment] 2018-06-21 01:06
Alright, fix as you see fit.

**Closed** 2018-06-21 02:08 UTC
Labels: fixed
