### ISSUE TITLE
[Ads] 1movies.is

### ISSUE THREAD

**Issue by ghajini** [NanoAdblocker/NanoFilters#250] opened 2019-01-01 16:06 UTC
### URLs where this issue occurs (Required)
`https://www2.1movies.is/movie/it-2017/111526/BLVQpMEv-watch-online-free.html`

### Describe the issue (Optional if obvious)
iam following issue on uassets tracker `https://github.com/uBlockOrigin/uAssets/issues/1648`

in this contributors are unable to reproduce the issue there so i ***asked for help here***
in this site currently whole player is blank....to get it to start i need to use exception filter
`@@||www2.1movies.is^$xmlhttprequest,domain=www2.1movies.is` to override existing easylist blocking filter `|https://*?$xmlhttprequest,domain=1movies.is|moviescouch.co|torrentfunk.com`

in doing so preroll/midroll ads get introduced despite `noopmp4-1s` scriptlet on that site
#### Environment (Required)

- Operating System and Version: windows 10
- Browser and Version: opera browser
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by jspenguin2017** [comment] 2019-01-01 16:43
I can't reproduce, the ads are correctly replaced by 1 second blank video. 
Closing as invalid as you did not fill the template.

**Comment by ghajini** [comment] 2019-01-01 17:31
advertisement of 2 sec is present in all videos at certain intervals
like 0:00 ,19:59 & so on.....would you check this,,,because its annoying to see that 4-5 times during video playback

**Comment by jspenguin2017** [comment] 2019-01-01 17:38
I usually don't really consider that to be a problem, but alright.

**Comment by ghajini** [comment] 2019-01-01 17:40
is it ok to see `loading ad` screen 5-7 times during the playback to you....if yes i wll close issue,,,,because low priority  issues are never fixed in this repo, frankly

**Comment by mapx-** [comment] 2019-01-01 17:42
I get only the normal 1s delay

**Comment by ghajini** [comment] 2019-01-01 17:44
that too 5-7 times during playback, does that sound not annoying

**Comment by jspenguin2017** [comment] 2019-01-01 17:46
Sure but it's once every 20 minutes, which is not enough to be a problem. The screen flashes 3 times an hour, which is acceptable. 

I agree that it should be fixed if easy, but right now, I have other things to do. You can speed up low priority issues by opening Pull Requests.

**Closed** 2019-01-01 17:48 UTC
Labels: low priority

**Comment by mapx-** [comment] 2019-01-01 17:50
@ghajini 
just add
```
||loadshare.org/custom/$media,redirect=noopmp4-1s,domain=1movies.se|1movies.to|1movies.is,badfilter
||loadshare.org/custom/$media,domain=1movies.se|1movies.to|1movies.is,important
```
