### ISSUE TITLE
[Anti-adblock] cbs.com

### ISSUE THREAD

**Issue by shayetft** [NanoAdblocker/NanoFilters#258] opened 2019-01-17 16:51 UTC
### Screenshots (Required)
![image](https://user-images.githubusercontent.com/46790449/51334019-f0b8f280-1a4c-11e9-8c53-3cf4b40995b9.png)

#### Environment (Required)

- Operating System and Version: Windows 7
- Browser and Version:  Chrome browser Version 71.0.3578.98
- Nano Adblocker Version:  Nano Adblocker v1.0.0.83
- Nano Defender Version (Optional if you are not using it): 15.0.0.87

#### Your filter lists (Required)

No change to the default settings (lists copied below) and auto-update filter lists is enabled

Nano Defender Integration​​​​​2,619 used out of 2,672​​​​
Nano filters​​​​​164 used out of 167​​​​
Nano filters – Whitelist​​​​​ 0 used out of 1​​​​
uBlock filters​​​​​ 13,175 used out of 13,185​​​​
uBlock filters – Badware risks ​​​​​47 used out of 47​​​​
uBlock filters – Privacy ​​​​​157 used out of 158​​​​
uBlock filters – Resource abuse​​​​​ 286 used out of 287​​​​
uBlock filters – Unbreak ​​​​762 used out of 764

#### Your custom filters (Required if you have any)
none

**Comment by jspenguin2017** [comment] 2019-01-18 02:37
I need a test link.

**Comment by jspenguin2017** [comment] 2019-01-18 03:09
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/4651

**Comment by jspenguin2017** [comment] 2019-01-18 03:09
Closing as duplicate because you did not fill the template.

**Closed by jspenguin2017** 2019-01-18 03:09 UTC
Labels: duplicate

**Comment by shayetft** [comment] 2019-01-18 14:40
i did fill the template. what is missing? i also toke a look at the duplicate you referenced. i tried the filters there. they still did not solve the problem

**Comment by jspenguin2017** [comment] 2019-01-19 01:49
You're missing test link and screenshot of console.

**Comment by arkayn71** [comment] 2019-01-20 04:56
Do you have the multipurpose filters checked, I had to have them active as well.
![screenshot_1](https://user-images.githubusercontent.com/14102543/51435458-ef4a1e80-1c34-11e9-81cb-2a32cb155698.png)
