### ISSUE TITLE
imgrock.pw

### ISSUE THREAD

**Issue by Madelnick** [NanoAdblocker/NanoFilters#333] opened 2019-05-19 00:10 UTC
imgView.net, https://imgrock.pw/ , https://imgtown.pw (they are sister sites).
I believe it was fixed for a brief moment but doesn't work anymore. Problem is that if Nano Adblocker is activated, one is redirected to websites such as istripper.com. If one disables the blocker, then the website work as intended but at the cost of trillion popups and ads.
Hopefully it can be fixed. Cheers!

#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by jspenguin2017** [comment] 2019-05-19 00:37
Can't reproduce. Closing as invalid as you did not fill the template.

**Closed by jspenguin2017** 2019-05-19 00:37 UTC
Labels: invalid

**Comment by LiCybora** [comment] 2019-05-20 04:05
I can reproduce the issue.

**Warn: The site is very nasty, and ads are likely NSFW, not sure if malicious.** Better test it on isolated environment to avoid possibly browser hijacking.


### URLs where this issue occurs (Required)
Generate via step of 2 Reproduction Steps.


### Screenshots (Required)
With Adblock (Note that adblocker is detected when clicking somewhere):
![image](https://user-images.githubusercontent.com/40160522/57995542-4386e180-7af5-11e9-8220-8fe0b45b7cef.png)

Without Adblock resulting NSFW and not posted here, but clicking anywhere result popup ads.

### Screenshot of console (Required, press `F12` to open the console)
With activated adblocker:
![image](https://user-images.githubusercontent.com/40160522/57995688-0d962d00-7af6-11e9-8489-73e6fcd71dd3.png)

Without activated adblocker (ND is activated):
![image](https://user-images.githubusercontent.com/40160522/57995715-3cac9e80-7af6-11e9-9364-d4921deae3b8.png)


### Describe the issue (Optional if obvious)


### Reproduction Steps (Optional if trivial)
1. Upload any image to https://imgrock.net
2. Copy the image link, then browse that link. You will be redirected to another URL as the screenshot.
3. Click `Continue to Image...`
4. With Adblocker on, it redirect to somewhere ads but never to the required image. Without adblocker (or whitelisted), the first click trigger many popups (while can be blocked by browser), and the second click redirect to corrected image.


### Anything else you believe to be useful (Optional)
From quick code review, the sites seems redirect links to another page when some ads script fails to be loaded.

#### Environment (Required)

- Operating System and Version: Windows 10 1804
- Browser and Version: Firefox 66.0.5
- Nano Adblocker Version: 1.0.0.109
- Nano Defender Version (Optional if you are not using it): 15.0.0.145

#### Your filter lists (Required)

Default.

**Comment by jspenguin2017** [comment] 2019-05-20 04:23
I received another report through Quick Issue Reporter, this one will be considered duplicate. https://github.com/NanoMeow/QuickReports/issues/1258
