### ISSUE TITLE
stern.de

### ISSUE THREAD

**Issue by n8v8R** [NanoAdblocker/NanoFilters#7] opened 2018-01-01 19:49 UTC
FF 57.03 x 64 with ND 13.16 on W10 x64 b16299

At first the site is loading correctly but then a short moment later reverting to notifying that adblocking is detected and thus access to content is limited

**Comment by jspenguin2017** [comment] 2018-01-01 20:13
Can't reproduce. Marking as invalid since you have not fill the template. 
![image](https://user-images.githubusercontent.com/7283682/34470742-76fc0640-eef5-11e7-8f06-050b80180056.png)

**Closed by jspenguin2017** 2018-01-01 20:13 UTC
