### ISSUE TITLE
[Anti-adblock] afdah.info

### ISSUE THREAD

**Issue by Cyberavater** [NanoAdblocker/NanoFilters#495] opened 2020-05-05 16:56 UTC
https://afdah.info/

**Comment by jspenguin2017** [comment] 2020-05-05 20:10
Can't reproduce anti-adblock. Also the site is marked as dangerous by Safe Browsing. 

Closing as invalid as you did not fill the template.

**Closed by jspenguin2017** 2020-05-05 20:10 UTC
Labels: invalid
