### ISSUE TITLE
[Anti-adblock] tune.pk

### ISSUE THREAD

**Issue by gluons** [NanoAdblocker/NanoFilters#24] opened 2018-01-30 16:25 UTC
### Describe the issue (Required)
[tune.pk](https://tune.pk/) prevents me to watch video in HD mode when adblocker enabled.

### URLs where this issue occurs (Required)
https://tune.pk/video/7539470/lost-love-intimes-ep1

### Screenshots (Required)
![default](https://user-images.githubusercontent.com/4688092/35576728-520d049a-0612-11e8-948a-b7aca0943052.PNG)

### Screenshot of console (Required, press `F12` to open the console)
![default](https://user-images.githubusercontent.com/4688092/35576869-b2a00ec4-0612-11e8-86f1-013d35b33871.PNG)

🗒 [Full log text](https://github.com/NanoAdblocker/NanoFilters/files/1678444/log.txt)

### Reproduction Steps (Optional if trivial)

Enter above site and click play button. Then change quality from **240** to **720**.

### Environment (Required)

- **Operating System and Version:** Windows 10 Pro 1709
- **Browser and Version:**  Firefox Nightly 60.0a1 (2018-01-30) - 64 bits
- **Nano Adblocker Version:**  1.0.0.28
- **Nano Defender Version:** 13.28

#### Your filter lists (Required)

![1](https://user-images.githubusercontent.com/4688092/35577562-74c135d6-0614-11e8-8bfe-545209550a8b.PNG)
![2](https://user-images.githubusercontent.com/4688092/35577569-77b3b76e-0614-11e8-9d2a-660a9650a06d.PNG)
![3](https://user-images.githubusercontent.com/4688092/35577575-79ff229c-0614-11e8-9d05-1d844eaa26e7.PNG)

#### Your custom filters (Required if you have any)
> Nope. I've **disable** all my custom rules before try it. 🙂

**Comment by jspenguin2017** [comment] 2018-01-30 18:41
Can't reproduce. Which other extensions do you have? 
![image](https://user-images.githubusercontent.com/7283682/35584519-7d8267f6-05b2-11e8-9f64-b523caaaaa19.png)

**Comment by gluons** [comment] 2018-01-31 14:10
These is all my installed add-ons/extensions:

- [Advanced GitHub Notifier](https://addons.mozilla.org/en-US/firefox/addon/advanced-github-notifier/)
- [Awesome Autocomplete for GitHub](https://addons.mozilla.org/en-US/firefox/addon/github-awesome-autocomplete/)
- [Emoji Cheatsheet](https://addons.mozilla.org/en-US/firefox/addon/emoji-cheatsheet/)
- [GitHub File Icon](https://addons.mozilla.org/en-US/firefox/addon/github-file-icon/)
- [GitHub Hovercard](https://addons.mozilla.org/en-US/firefox/addon/github-hovercard/)
- [YouTube in HD (720p, 1080p, 1440p, 2160p)](https://addons.mozilla.org/en-US/firefox/addon/youtube-hd-1/)
- [HTTPS Everywhere](https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/)
- [Linkificator](https://addons.mozilla.org/en-US/firefox/addon/linkificator/)
- [Nano Adblocker](https://addons.mozilla.org/en-US/firefox/addon/real-nano-adblocker/) 🌟
- [Nano Defender](https://addons.mozilla.org/en-US/firefox/addon/real-nano-defender/) 🌟
- [No Coin](https://addons.mozilla.org/en-US/firefox/addon/no-coin/)
- [npm-hub](https://addons.mozilla.org/en-US/firefox/addon/npm-hub/)
- [OctoLinker](https://addons.mozilla.org/en-US/firefox/addon/octolinker/)
- [Octotree](https://addons.mozilla.org/en-US/firefox/addon/octotree/)
- [Popup Blocker Ultimate](https://addons.mozilla.org/en-US/firefox/addon/popup-blocker-ultimate/)
- [Privacy Badger](https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/)
- [React Developer Tools](https://addons.mozilla.org/en-US/firefox/addon/react-devtools/)
- [Reddit Enhancement Suite](https://addons.mozilla.org/en-US/firefox/addon/reddit-enhancement-suite/)
- [Refined GitHub](https://addons.mozilla.org/en-US/firefox/addon/refined-github-/)
- [Share Backported](https://addons.mozilla.org/en-US/firefox/addon/share-backported/)
- [Stylus](https://addons.mozilla.org/en-US/firefox/addon/styl-us/)
- [To Google Translate](https://addons.mozilla.org/en-US/firefox/addon/to-google-translate/)
- [Video DownloadHelper](https://addons.mozilla.org/en-US/firefox/addon/video-downloadhelper/)
- [Violentmonkey](https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/)
- [Vue.js devtools](https://addons.mozilla.org/en-US/firefox/addon/vue-js-devtools/)

**Comment by jspenguin2017** [comment] 2018-01-31 15:10
Try a new profile with just Nano Adblocker and Nano Defender. You have way too many extensions, it's likely to be an issue elsewhere.

**Comment by gluons** [comment] 2018-02-02 09:01
Still happen with new Firefox profile.
My new profie just has Nano Adblocker and Nano Defender with default filters.

![default](https://user-images.githubusercontent.com/4688092/35724898-f1718d32-0831-11e8-8cec-f171023f6c80.PNG)

![image](https://user-images.githubusercontent.com/4688092/35724952-19254d3c-0832-11e8-9b03-bf061394cebb.png)

**Comment by jspenguin2017** [comment] 2018-02-02 13:49
Something blown up for nightly, I'll close this as browser bug. 
https://github.com/gorhill/uBlock/issues/3474

**Closed** 2018-02-02 13:50 UTC
Labels: browser bug

**Comment by gluons** [comment] 2018-02-02 13:53
OK. Thank you very much for clarification.
I'll move back to Firefox **Stable** haha

**Comment by gluons** [comment] 2018-02-02 13:55
Yeah! It works fine in Firefox Stable. 😄 🎉
