### ISSUE TITLE
[Annoyance, Cookie Wall] fortune.com

### ISSUE THREAD

**Issue by hawkeye116477** [NanoAdblocker/NanoFilters#96] opened 2018-06-06 10:27 UTC
### URLs where this issue occurs (Required)

`http://fortune.com/2016/11/14/gitlab-cloud-storage/`
### Screenshots (Required)
![screenshot_20180606_121840](https://user-images.githubusercontent.com/19818572/41032470-c3d0f986-6983-11e8-85c4-9302cc2c6ce9.png)

### Screenshot of console (Required, press `F12` to open the console)
For this I think that's not needed.

### Describe the issue (Optional if obvious)
Privacy Policy/GDPR message. I need to click continue to go to the right page.

#### Environment (Required)

- Operating System and Version: Manjaro Linux
- Browser and Version: Vivaldi 1.15.1147.42 (based on Chromium 65.0.3325.183)
- Nano Adblocker Version: 1.0.0.52
- Nano Defender Version (Optional if you are not using it): 

#### Your filter lists (Required)
Nano Annoyance, uBlock Annoyance and few others, but for this it's probably not that important, cuz rather only auto click rule can help here.

**Comment by jspenguin2017** [comment] 2018-06-06 13:16
I couldn't reproduce this, does this only happen to EU users?

**Comment by jspenguin2017** [comment] 2018-06-07 00:20
OK, reproduced with EU VPN, but the button isn't available when `DOMContentLoaded` event is fired. 

I'm having a lot of trouble dealing with these innovative cookie walls...

**Comment by jspenguin2017** [comment] 2018-06-09 02:58
Fixed by new script snippet `nanop-click-elements-onload.js`

**Closed** 2018-06-09 02:58 UTC
Labels: fixed, geolock

**Comment by jspenguin2017** [comment] 2018-06-09 03:37
It takes like 2 seconds to kick in, I guess it's only useful to people to clear cookies on browser exit.
