### ISSUE TITLE
[Anti-adblock] uitzendinggemist.net

### ISSUE THREAD

**Issue by Sopor** [NanoAdblocker/NanoFilters#310] opened 2019-04-18 11:39 UTC
![image](https://user-images.githubusercontent.com/5789283/56358516-1c2fb280-61df-11e9-9969-30a575c6369a.png)

Environment (Required)
Operating System and Version: Windows 10
Browser and Version: Firefox 66.0.3
Nano Adblocker Version: uBlock origin 1.18.16
Nano Defender Version (Optional if you are not using it): 15.0.0.129
Your filter lists (Required)
SWE: Frellwit's Swedish Filter​​​​​

**Comment by jspenguin2017** [comment] 2019-04-19 02:33
Can't reproduce. Closing as invalid as you did not fill the template. 
![image](https://user-images.githubusercontent.com/7283682/56402117-48682500-6219-11e9-8562-ffa6d4f67af7.png)

**Closed by jspenguin2017** 2019-04-19 02:33 UTC
Labels: invalid

**Comment by Sopor** [comment] 2019-04-22 12:38
What did a not filled in the template? I get the adblock in Firefox and Chrome https://www.uitzendinggemist.net/aflevering/472896/Hart_Van_Nederland.html

**Comment by mapx-** [comment] 2019-04-22 13:08
fixed, but when I test the video (**even disabling uBo**) I get a message like "video does not exist anymore"

**Comment by Sopor** [comment] 2019-04-22 13:36
@mapx- yes, i believe that is because you are GEO blocked ...

**Comment by mapx-** [comment] 2019-04-22 13:37
well, does you confirm the fix is ok ?

**Comment by Sopor** [comment] 2019-04-22 13:43
Yes, it seems to work 👍

**Comment by jspenguin2017** [comment] 2019-04-23 00:54
You were missing the test link. Anyway, looks like it's now fixed upstream.
