### ISSUE TITLE
[Anti-adblock] derstandard.at

### ISSUE THREAD

**Issue by Esokrates** [NanoAdblocker/NanoFilters#149] opened 2018-07-26 11:42 UTC
Sorry, I do not want to fool you guys, but the issue is not solved for real, locking as solved does not make it any better.
I do not use any Apple device.

Here is a screencast I just recorded for proof when launching chromium with a fresh profile:
https://youtu.be/JR-NgxfAuIc

I am happy to give you any info you need.

**Comment by okiehsch** [comment] 2018-07-26 21:44
I don't know what tot tell you, I can't reproduce.

I use the site frequently and I never have any issue unless I disable `uBO-filters` at which point I get the adblock message within three or four clicks.

**Comment by jspenguin2017** [comment] 2018-07-26 23:55
Can you try Chromium on Ubuntu?

**Comment by okiehsch** [comment] 2018-07-27 00:05
My standard "private" setup is Linux Manjaro Chrome/Chromium and that does not have any issues.

I can't install Ubuntu right now.

**Comment by jspenguin2017** [comment] 2018-07-27 00:31
Hum, I can't reproduce it neither... My only worry is that `set-constant` could fail the race.

**Comment by okiehsch** [comment] 2018-07-27 00:38
That's easy to check.
@Esokrates does adding
````
derstandard.at#@#script:inject(set-constant.js, nuggprof, noopFunc)
@@||derstandard.nuggad.net/rc$script,domain=derstandard.at
````
to your filters fix the issue on your end.

**Comment by jspenguin2017** [comment] 2018-07-27 00:39
I don't see the page defining a function called `nuggprof` on my end.

**Comment by jspenguin2017** [comment] 2018-07-27 01:02
It's working for me with or without the scriptlet.

**Comment by okiehsch** [comment] 2018-07-27 01:18
Hm, if I disable the scriptlet after clicking on a few articles
![image](https://user-images.githubusercontent.com/16838044/43296382-521f2034-914b-11e8-8c6e-67b4f1554c5f.png)

I don't know what to make of all this, I do know that it does make it nearly impossible to find a reliable fix that works for everybody.

**Comment by lain566** [comment] 2018-07-27 09:36
I can reproduce it using the default settings in both uBO and Nano

![derstandard at_-_pur_-_derstandard at_-_chromium_2018-07-27_11-09-52](https://user-images.githubusercontent.com/27441315/43312499-cb0d25d0-918d-11e8-8e7e-dadce46e2eef.png)

![derstandard at_-_pur_-_derstandard at_-_chromium_2018-07-27_10-05-21](https://user-images.githubusercontent.com/27441315/43312508-d260d700-918d-11e8-91a7-4d6551f2ca52.png)

**Comment by Esokrates** [comment] 2018-07-27 09:56
Same here, fully updated extensions (using 15.0.0.19), cleared cookies.
It takes some minutes, but it reliably triggers :-(.

**Comment by Esokrates** [comment] 2018-07-27 10:13
@okiehsch I just tried your scriptlet: does not make a difference, the paywall triggers reliably after a few minutes at the latest.

**Comment by Esokrates** [comment] 2018-07-27 10:43
Upgraded to chromium 68.0.3440.75, does not make a difference, I can 100% reproduce, just a matter of time.

**Comment by Esokrates** [comment] 2018-07-27 10:52
@okiehsch Also tried fresh profile with ublock origin + ublock origin extra: same issue.

**Comment by jspenguin2017** [comment] 2018-07-27 13:16
I don't know what to tell you, I can't reproduce. The only problem I can think of is the race condition in that scriptlet. Which should be fixed now. 

Which country are you in? Can you dump the logger output?

**Comment by Esokrates** [comment] 2018-07-27 14:29
@jspenguin2017 I am located in Austria. I am not aware of my ISP censoring anything, nor do I have any sort of network filtering activated. 
What logger output do you need / what do you mean by logger output?
Regarding DevTools console output: would a screencast do it? I have the console open and trigger the paywall and you can follow along the output?

**Comment by lain566** [comment] 2018-07-27 20:06
I can reproduce it immediately using the following steps: 
 Go to `derstandard.at`
 Refresh page 4 or 5 times

**Comment by okiehsch** [comment] 2018-07-27 20:36
You are right, I can reproduce if I refresh the homepage  page 4 or 5 times.
If I refresh any article I can't reproduce.
Example: 
````
https://derstandard.at/2000083972831/Vettel-Ich-glaube-nicht-dass-es-ein-grosser-Fehler-war
````
![unbenannt](https://user-images.githubusercontent.com/16838044/43345348-78c5c844-91ed-11e8-875b-37957c98d7ad.JPG)

This is some weird detection mechanism and I can't believe that it is working as intended.

**Comment by Esokrates** [comment] 2018-07-27 22:20
Confirming the observation that refreshing the main page 4 to 5 times triggers the issue.

**Comment by jspenguin2017** [comment] 2018-07-28 00:05
OK, so the problem is just with the home page.

**Comment by okiehsch** [comment] 2018-07-28 00:34
Well, it is only if you refresh it 4-5 times in a row.
If I for example go to the homepage, then click an article, go back to the homepage, click another article etc. I can't reproduce.
That's why I never had any issue using the site, as no "normal" user refreshes the homepage just for the fun of it.

**Comment by jspenguin2017** [comment] 2018-07-28 00:54
True, but if you have no extension enabled, refreshing 4-5 times won't send you to the block page.

**Comment by okiehsch** [comment] 2018-07-28 01:05
`@@||adfarm1.adition.com/s$script,domain=derstandard.at`
fixes the issue, but I am hesitant to add an exception for such a franly bizarre case.

**Comment by okiehsch** [comment] 2018-07-28 01:30
The homepage with the exception.
![image](https://user-images.githubusercontent.com/16838044/43351714-6a479ef4-9216-11e8-9eea-817d59d56046.png)

The homepage witout the exception
![image](https://user-images.githubusercontent.com/16838044/43351722-94b4a8da-9216-11e8-9d7a-ed9e41fdee2e.png)

**Comment by okiehsch** [comment] 2018-07-28 01:32
The "Bezahlte Anzeige" is an ad.

**Comment by jspenguin2017** [comment] 2018-07-28 01:37
Interesting, they didn't come up before.

**Comment by jspenguin2017** [comment] 2018-07-28 01:39
Should be good now.

**Comment by okiehsch** [comment] 2018-07-28 01:40
The exception is really not a good idea, go to `https://derstandard.at/Inland` and wait a little.
The ad is quite obvious on that page ;)

**Comment by Esokrates** [comment] 2018-07-28 09:42
Bad News: Using Nano Defender 15.0.0.20 reloading 4 times does still trigger the issue, tested with fresh profile.

**Comment by jspenguin2017** [comment] 2018-07-28 15:10
> tested with fresh profile.

Don't, you need to update filters. 

But yea, it somehow still triggers, but it's gone after a few seconds.

**Comment by okiehsch** [comment] 2018-07-28 15:19
Force an update of `uBO-filters` and then add
`derstandard.at##script:inject(cookie-remover.js, /^MGUID/)`
to your filter list.

**Comment by jspenguin2017** [comment] 2018-07-28 15:56
Does that break login?

**Comment by okiehsch** [comment] 2018-07-28 16:18
I can login, the problem is that I get automatically logged out if I refresh the page.

**Comment by Esokrates** [comment] 2018-07-28 20:15
@okiehsch Adding
`derstandard.at##script:inject(cookie-remover.js, /^MGUID/)
`
fixes the reloading issue yes, but I can still trigger the issue when aggressively clicking through articles randomly for at most 4 minutes, any idea?

**Comment by Esokrates** [comment] 2018-07-30 19:30
@okiehsch Thanks for pointing this out. I just recorded yet again how I am able to reproduce:
https://youtu.be/cauubMXgn1s
If you want I can also demonstrate this with an ublock setup. I am always successful within a 5 minute timeframe. Tested on two different networks.

**Comment by okiehsch** [comment] 2018-07-30 19:37
The moment you get the anti-adblock message, what does your logger show?

**Comment by Esokrates** [comment] 2018-07-30 19:48
Found the way to trigger it, click exactly as in the screencast (demonstrated that ublock and nano behave exactly the same):
https://youtu.be/WAvYM49PBuY
https://youtu.be/xGv3KBaBDdY
The trick is to use the uppermost navigation bar, which triggers the issue within 4 clicks.
Regarding the logger (by which I suppose you mean the console): there are only unrelated vsync errors.

**Comment by okiehsch** [comment] 2018-07-30 19:59
I mean [uBlockOrigins logger](https://github.com/gorhill/uBlock/wiki/The-logger).

**Comment by okiehsch** [comment] 2018-07-30 20:01
> EDIT: BTW, the 5 times reloading triggers the issue again!!

With
`derstandard.at##script:inject(cookie-remover.js, /^MGUID/)`
added to your filter list?

**Comment by Esokrates** [comment] 2018-07-30 20:16
@okiehsch I've added a second EDIT to my comment.
Now I have recorded another screencast with the line added to my filter list, force updated filters and the logger open, please have a look:
https://youtu.be/2nb0-B5UvVY

**Comment by okiehsch** [comment] 2018-07-30 20:30
Ok, this is the same output that I get if I remove 
`derstandard.at##script:inject(cookie-remover.js, /^MGUID/)`

Now, no need for a screencast, just open your logger and put `--` in the "filter log entries" box.

Trigger the anti-adblock message and post a screenshot of the logger after you successfully triggered it.

**Comment by Esokrates** [comment] 2018-07-30 20:37
Because I've already uploaded here another link for a screencast where I triggered:
https://youtu.be/z0c_VCGFKLY
Here a screenshot of another try as you requested:
![screenshot from 2018-07-30 22-34-47](https://user-images.githubusercontent.com/17780185/43422137-185f6efc-9449-11e8-8989-e7bfe7eec2b8.png)

**Comment by okiehsch** [comment] 2018-07-30 20:42
Well, adding
`@@||adfarm1.adition.com/s$script,domain=derstandard.at`
to your filter list should work.

The message should change to

![unbenannt1](https://user-images.githubusercontent.com/16838044/43422381-d2cc2ee2-9449-11e8-9452-7de98002a74d.JPG)

and then to
![image](https://user-images.githubusercontent.com/16838044/43422353-bc3bb080-9449-11e8-909a-12726df70521.png)

**Comment by Esokrates** [comment] 2018-07-30 20:49
@okiehsch Well, when adding that to my filters I can recover from the paywall yes, but the articles break after a few seconds like:
![screenshot from 2018-07-30 22-49-06](https://user-images.githubusercontent.com/17780185/43422675-c9193272-944a-11e8-8015-97c6d0587cf4.png)
I'll do further tests.

**Comment by okiehsch** [comment] 2018-07-30 20:52
Add
`derstandard.at##iframe[src="about:blank"]`

**Comment by Esokrates** [comment] 2018-07-30 20:54
That works :-).
I'll do further testing.

**Comment by Esokrates** [comment] 2018-07-30 21:11
@okiehsch It still triggers but recovers afterwards as you pointed out, but I guess that's the best you can do!?

**Comment by okiehsch** [comment] 2018-07-30 21:16
I can't reproduce, so yes that is the best I can do.

**Comment by Esokrates** [comment] 2018-07-30 21:54
Ok, shall I do something else? Here how it looks after triggering with all the lines you provided:

![screenshot from 2018-07-30 23-48-55](https://user-images.githubusercontent.com/17780185/43425623-7ab624ce-9453-11e8-97c0-6262bd9ffc75.png)
At this point I have clicked nothing
![screenshot from 2018-07-30 23-48-57](https://user-images.githubusercontent.com/17780185/43425641-891c4f20-9453-11e8-849e-7779c81874b9.png)
![screenshot from 2018-07-30 23-49-03](https://user-images.githubusercontent.com/17780185/43425658-9850737c-9453-11e8-8a0a-42ecc6359b7a.png)
Here I clicked to return to the article:
![screenshot from 2018-07-30 23-49-22](https://user-images.githubusercontent.com/17780185/43425674-a7f72690-9453-11e8-9e60-dd587289718f.png)


Really strange that you can't reproduce, did you try really hard for a few minutes?

**Comment by Esokrates** [comment] 2018-07-30 22:16
@okiehsch Regarding your comment that the anti-adblock script is broken in the first place: As someone who understands German it does not look like it: The second screenshot in my previous comment (Bitte ein wenig Geduld, Ihr Adblocker-Status wird überprüft) states "Patience, your adblocker status is checked", so it checks if you have whitelisted the site in the meantime.
This check occured previously too if a certain timeout was reached I think, but the test always failed and the paywall remained. 

Do you think the cookie-removed could be adapted to work more reliable in order to not trigger the paywall in the first place like @gwarser pointed out?

**Comment by okiehsch** [comment] 2018-07-30 22:26
> As someone who understands German it does not look like it

I know hat the messages state ;)
My opinion:

Es macht wenig Sinn zu prüfen ob ein bestimmtes script geladen werden konnte und dann, nach erfolgter Erkennung, das Erlauben eines anderen script's zum Anlass zu nehmen die Seite doch zu zeigen.

**Comment by okiehsch** [comment] 2018-07-30 22:29
> Ok, shall I do something else?

I have said all there is to say, I can't reproduce.

**Comment by jspenguin2017** [comment] 2018-07-31 00:03
If you don't have adblocker active, does the site still redirect you to the block screen? If yes, I will add the workaround to the whitelist filter.

**Comment by Esokrates** [comment] 2018-07-31 09:54
@okiehsch Have you tried using a VPN?
@jspenguin2017 Without adblocker no block screen for me.

**Comment by Esokrates** [comment] 2018-07-31 10:04
@okiehsch Also, maybe we could do something else in terms of reproduction: Would you be able to boot a live image in a virtual machine so that we have exactly the same software running in order to find the reason why we have different results?

**Comment by okiehsch** [comment] 2018-07-31 20:30
My last comment on this topic:

> I am always successful within a 5 minute timeframe.
> It still triggers but recovers afterwards

I will not try clicking maniacally through articles for minutes at a time on the off chance that I can reproduce an `anti-adblock` message, which I will then recover from immediately.

Like I repeatedly said, I use the site frequently and have **no issues**, though I do not refresh the same pages five times in a row or click frantically through numerous articles.

If there is a better cookie-fix, I will post it.

I will unsubscribe from this topic, please do not ping me.

**Comment by Esokrates** [comment] 2018-07-31 22:31
Okay thank you very much for your support.
I use the site frequently as well and I do get the problem without "clicking maniacally through articles for minutes", I did that just for testing and for showing you guys that the issue triggers in a sensible timeframe. 

I can understand that you do not have the motivation to click randomly on some page in order to trigger some issue, but as I clearly showed it works. I thought this would be helpful for your to find a way to fix that.

@jspenguin2017 Could you include the workaround found in this thread?
`derstandard.at##script:inject(cookie-remover.js, /^MGUID/)
@@||adfarm1.adition.com/s$script,domain=derstandard.at
derstandard.at##iframe[src="about:blank"]
`
My testing showed that sometimes a page gets bigger as if some elements were not hidden (no ads get through though)  but that issue disappears within seconds.

**Comment by jspenguin2017** [comment] 2018-08-01 00:09
The cookie removing filter breaks login. So no. 

I want to see if it can be fixed with monkey patching, if the whitelist doesn't always work, I rather not include it.

**Comment by MaxValue** [comment] 2018-11-12 21:44
I have currently this same problem, I tried all the rules in this thread (also all of them together), but it still gives me the paywall.

But: On reddit I found [this thread](https://www.reddit.com/r/Austria/comments/8hf3um/). This guy made [a user script](https://gir.st/blog/fairblock.user.js) which essentially does the same as the scriptlet (it also deletes the "PurWallHit" cookie, but this cookie was never relevant).

So my point is: _Maybe the scriptlet does not work at all?_

I tested this with reddit, adding a rule to delete the "reddit_session" cookie. If it would work, it should always keep me logged out, which it does not since I was still logged in there (even after visiting multiple pages, reopening and closing the filter list).

**Comment by jspenguin2017** [comment] 2018-11-12 22:17
@MaxValue Removing the `MGUID` cookie probably will log you out though.

**Comment by jspenguin2017** [comment] 2018-11-12 22:42
You're right, there is a problem with the scriptlet. It doesn't quite handle domain properly. 

The scriptlet will set cookie for `www.reddit.com` and `.www.reddit.com` but it should be `.reddit.com`. 

@gorhill FYI.

**Comment by jspenguin2017** [comment] 2018-11-12 22:46
Doesn't really matter though, I can always add a new script snippet to Nano Resources. The reason I didn't land the fix is that I'm not sure if deleting `MGUID` will break login.

**Comment by MaxValue** [comment] 2018-11-12 22:53
Yes, I just checked it - deleting MGUID will break login (the user is logged out on next request).

**Comment by MaxValue** [comment] 2018-11-13 01:03
Something else: I think that getting cookie-remover working is preeetty important for the future of ad blocking. What derstandard.at does makes totally sense and other sites will do the same in the future: 

Force the user to have cookies enabled (because of the privacywall at first visit) and then use a HttpOnly cookie (which you cannot manipulate over simple JavaScript) which you use to track the users' usage of the site. And by tracking I mean here counting the number of seen articles.

So what this scriptlet (or any other similar envisioned feature) should be able to do is allowing filter lists to edit/delete both kinds (normal and HttpOnly) of cookies. Other extensions (cookie editors) can very well edit HttpOnly cookies. Making a userscript for every website which uses this trick defeats the purpose of adblocking extensions.

**Comment by jspenguin2017** [comment] 2018-11-13 02:17
Not really, I don't think we ever needed that cookie remover scriptlet, and even if it worked as expected, it wouldn't be an ideal solution for this issue. 

Maybe breaking login isn't an issue for you, but that can't be considered OK in general.

**Comment by MaxValue** [comment] 2018-11-13 02:23
You are right.

So this leaves no solution I guess. Blocking/deleting cookies disables the website, sooo what now?

**Comment by jspenguin2017** [comment] 2018-11-13 02:24
If I understood right, the anti-adblock screen only show if you refresh the home page 5 times, which I don't think that can happen during normal use.

**Comment by MaxValue** [comment] 2018-11-13 02:31
No, this is a sort of freemium model: The site tracks the user and if they read too many articles (about more than 4), it gives you this paywall, because your _trial_ ended. Maybe it is indeed duty cycle based, meaning it will go away after some time, but I doubt this.

I think this paywall comes anyways, no matter how slow you navigate. Of course, maybe if you navigate _extremly_ slow around the site it will not come up, because you are not hitting the duty cycle. I will test this in the next time and let you know if it doesn't come up.

**Comment by jspenguin2017** [comment] 2018-11-13 02:31
Actually, the behavior of `cookie-remover.js` does match its documentation. Although I agree that it is pretty useless in its current form.

**Comment by jspenguin2017** [comment] 2018-11-13 02:40
Can't reproduce. If I navigates over articles, I get no anti-adblock wall.

**Comment by jspenguin2017** [comment] 2019-02-28 04:38
Fixed here: https://github.com/uBlockOrigin/uAssets/commit/ea3c7777c5994f6558176d06a3a2cba6be41eae6

**Closed by jspenguin2017** 2019-02-28 04:38 UTC
Labels: fixed
