### ISSUE TITLE
[Anti-adblock / Annoyance] italiashare.life

### ISSUE THREAD

**Issue by giampi75** [NanoAdblocker/NanoFilters#18] opened 2018-01-16 11:13 UTC
www.italiashare.life

![italiashare](https://user-images.githubusercontent.com/17108055/34985898-ed0c8a8c-fab5-11e7-95e6-f660f2745406.jpg)

Firefox Nightly 59
uBlock origin

**Comment by jspenguin2017** [comment] 2018-01-16 15:00
@okiehsch 
This is fixed in Nano Defender, so I'll leave this to you. It's quite tricky btw. 
```js
if (a.domCmp(["dasolo.co", "dasolo.me", "italiashare.info", "italiashare.life"])) {
    //https://github.com/jspenguin2017/uBlockProtector/issues/126
    a.inject(() => {
        "use strict";
        window.eval = () => { };
    });
    a.noAccess("adblockblock");
    a.noAccess("alert");
    a.bait("div", "#loveyou");
    //https://github.com/jspenguin2017/uBlockProtector/issues/280
    a.readOnly("nocontext", null);
    a.readOnly("mischandler", null);
    a.readOnly("disableselect", null);
    a.readOnly("disabletextselect", null);
    a.filter("addEventListener", a.matchMethod.stringExact, "contextmenu", "window.document");
    a.on("load", () => {
        a.inject(() => {
            "use strict";
            window.document.oncontextmenu = null;
            window.document.onmousedown = null;
            window.document.onmouseup = null;
            window.setTimeout(() => {
                window.$("body").unbind("contextmenu");
                window.$("#id").unbind("contextmenu");
            }, 250);
        });
    });
}
```

**Comment by okiehsch** [comment] 2018-01-16 18:45
I can't reproduce the anti-adblock with Chrome or Firefox, the site works fine on my end.

I fixed the right-click annoyance a few weeks ago and it still works on my end, do you have
uBlock-annoyances enabled?
https://github.com/uBlockOrigin/uAssets/blob/master/filters/annoyances.txt#L34

**Closed** 2018-01-16 19:37 UTC
Labels: fixed in Nano Defender
