### ISSUE TITLE
salon.com

### ISSUE THREAD

**Issue by nanorocks1** [NanoAdblocker/NanoFilters#29] opened 2018-02-13 19:57 UTC
Hi,

I have used your product for a while now and it is great. I cannot surf without it. I noticed something today that when I was on salon.com, I got a popup saying that I was using an adblocker. First time I have seen this in a while. Is there something I have to do to prevent this?

I am using Chrome with ublock and I looked at the instructions and have all the filters installed. Thanks.

N

### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version:

**Comment by jspenguin2017** [comment] 2018-02-13 21:52
Duplicate of https://github.com/jspenguin2017/uBlockProtector/issues/858

**Closed by jspenguin2017** 2018-02-13 21:52 UTC
Labels: duplicate
