### ISSUE TITLE
[Ads] dropapk.to

### ISSUE THREAD

**Issue by Cyberavater** [NanoAdblocker/NanoFilters#504] opened 2020-05-20 15:26 UTC
Eg link: https://dropapk.to/fmp856w0t45r
OS: Android 9
Pop-up ads at last moment of download.

**Comment by jspenguin2017** [comment] 2020-05-20 23:24
Can't reproduce. Closing as invalid since you did not fill the template.

**Closed by jspenguin2017** 2020-05-20 23:24 UTC
Labels: invalid
