### ISSUE TITLE
[Anti-adblock] uploadship.com

### ISSUE THREAD

**Issue by Signup-pawan** [NanoAdblocker/NanoFilters#422] opened 2019-11-10 17:10 UTC
### URLs where this issue occurs (Required)

https://www.uploadship.com/4ec9f50675d566f1

### Screenshots (Required)

![image](https://user-images.githubusercontent.com/55138565/68547608-802ef800-0409-11ea-92d0-c4d4746a820c.png)

### Screenshot of console (Required, press `F12` to open the console)

![image](https://user-images.githubusercontent.com/55138565/68547635-c8e6b100-0409-11ea-9216-bc98ebc40e11.png)

### Describe the issue (Optional if obvious)
Asking for disable the adblock and restricts the downloads until we disable the adblock and refresh the page without adblock.
#### Environment (Required)

- Operating System and Version:  Microsoft Windows 10 Pro & 10.0.18362 Build 18362
- Browser and Version: Chrome 78.0.3904.97
- Nano Adblocker Version: 1.0.0.128
- Nano Defender Version (Optional if you are not using it): 15.0.0.169

#### Your filter lists (Required)

![image](https://user-images.githubusercontent.com/55138565/68547720-cb95d600-040a-11ea-81a8-eacc854f3f5c.png)

#### Your custom filters (Required if you have any)
**None**

![image](https://user-images.githubusercontent.com/55138565/68547735-f122df80-040a-11ea-8ab7-b219c532a166.png)

#### Your other extensions (Required if you have any)

![image](https://user-images.githubusercontent.com/55138565/68547743-08fa6380-040b-11ea-8a53-c0ed2a722c4c.png)

**Comment by jspenguin2017** [comment] 2019-11-10 17:46
Duplicate of https://github.com/NanoMeow/QuickReports/issues/2058

**Closed by jspenguin2017** 2019-11-10 17:46 UTC
