### ISSUE TITLE
[Anti-adblock] browserleaks.com

### ISSUE THREAD

**Issue by trytip** [NanoAdblocker/NanoFilters#340] opened 2019-05-26 15:27 UTC
### Describe the issue (Required)
NanoDefender does not protect chrome any longer, it is detected at browserleaks.com/proxy

### Screenshots (Required)
https://i.imgur.com/NdzGDZv.jpg
![Selection_002](https://user-images.githubusercontent.com/34773669/58383787-964a1880-7f8f-11e9-8e48-b029935f3947.jpg)

### Screenshot of console (Required, press `F12` to open the console)
![Content Filtering Proxy Detection - AdBlock](https://user-images.githubusercontent.com/34773669/58383816-e032fe80-7f8f-11e9-98de-4bc2487e107f.jpg)

### URLs where this issue occurs (Required if applicable)
https://browserleaks.com/proxy

### Reproduction Steps (Optional if trivial)

go to the link above to check detection of adblocker.  used to show not detected in all fields, but no longer

#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by jspenguin2017** [comment] 2019-05-26 17:05
Duplicate of https://github.com/NanoMeow/QuickReports/issues/903

**Closed by jspenguin2017** 2019-05-26 17:05 UTC
Labels: duplicate
