### ISSUE TITLE
voot.com

### ISSUE THREAD

**Issue by sasha008** [NanoAdblocker/NanoFilters#194] opened 2018-10-16 13:08 UTC
Hi,

Link of sample video - https://www.voot.com/shows/mtv-roadies-xtreme/16/567520/did-harpwit-cross-the-line-/570738

Screenshot of the issue - https://i.imgur.com/FDrKwY0.jpg

Screenshot of console - https://i.imgur.com/Y9AQB6x.jpg

Issue - Videos on voot.com show the anti-adblock warning to disable adblock.

#### Environment (Required)

- Operating System and Version: Windows 10 pro (64 bit)
- Browser and Version: Chrome Version 69.0.3497.100
- Nano Adblocker Version: 1.0.0.71
- Nano Defender Version : 15.0.0.57

#### Your filter lists (Required)

Built-in (8/11)
Nano Defender Integration​​​​​
Nano filters​​​​​
Nano filters – Whitelist​​​​​
uBlock filters​​​​​
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse
uBlock filters – Unbreak​​​​​

Ads (2/4)
Adblock Warning Removal List
EasyList​​​​​

Privacy (1/3)
EasyPrivacy

Malware domains (2/4)
Malware Domain List​​​​​
Malware domains​​​​​

Multipurpose (1/5)
Peter Lowe’s Ad and tracking server list​​​​​

Custom (1/1)
Nano filters – Timer bypassing (sometimes works)​​​​​0 used out of 0​​

**Comment by jspenguin2017** [comment] 2018-10-16 14:04
Duplicate of https://github.com/NanoMeow/QuickReports/issues/207

**Closed by jspenguin2017** 2018-10-16 14:04 UTC

**Comment by jspenguin2017** [comment] 2018-10-16 18:44
Requires account. See issue linked above.
