### ISSUE TITLE
[Anti-adblock] topflix.tv

### ISSUE THREAD

**Issue by fabiobarao94** [NanoAdblocker/NanoFilters#380] opened 2019-07-24 18:20 UTC
-->
### URLs where this issue occurs (Required)
 https://topflix.tv
Use the domain as the title
--> https://topflix.tv

i even tried script safe to block scripts, this site has protection to prevent F12 inspect
usually i can bypass many websites that blocks adblocker
but this one is killing me, this is one of those powerfull ones, so please can you help
me, so me and more people can unblock this web site

### Screenshot of console (Required, press `F12` to open the console)
![image](https://user-images.githubusercontent.com/15664251/61817439-75465c80-ae46-11e9-983c-54231a4b87d5.png)

it does'nt let you watch the player

#### Environment (Required)

- Operating System and Version: 
Windows 10 Pro Version 10.0.17763 N/A Build 17763
- Browser and Version: 
chrome Versão 75.0.3770.142 (Versão oficial) 64 bit
- Nano Adblocker Version: 
adblock Versão 3.49.1

#### Your filter lists (Required)
EasyList
Filtros antifraude
Filtros personalizados do AdBlock
EasyPrivacy (proteção de privacidade)
Fanboy's Annoyances
Lista AdBlock Warning Removal
Lista de Proteção Contra Mineração de Criptomoedas (Bitcoin)
Lista de filtros antisocial
Proteção de malwares
EasyList Portuguese+EasyList
AakList (Anti-Adblock Killer)

#### Your other extensions (Required if you have any)
tempermonkey 
script unlock right click

**Comment by mapx-** [comment] 2019-07-24 18:46
no anti adb for me, try using default settings (and remove aak list => outdated, obsolete)

**Comment by fabiobarao94** [comment] 2019-07-25 00:04
> no anti adb for me, try using default settings (and remove aak list => outdated, obsolete)

I tried what you said, still didn't work, the message still appears, this is very annoying

**Comment by LiCybora** [comment] 2019-07-25 02:07
From the screenshot and environment provided by OP, he is using Adblock instead of Nano/uBo. He don't even subscribe any uBlock/Nano Filters from his provided filter lists.

Nothing we can fix if OP don't use our adblocker and filter list.

**Comment by fabiobarao94** [comment] 2019-07-25 10:10
i even tried nano adblock extension default with the same result, the page still appears

**Comment by mapx-** [comment] 2019-07-25 10:21
- disable / remove adblock / ABP
- use only uBo / nano

**Comment by fabiobarao94** [comment] 2019-07-25 10:22
> * disable / remove adblock / ABP
> * use **only** uBo / nano

i  tried nano adlbock and the page still goes to that message

**Comment by fabiobarao94** [comment] 2019-07-25 10:23
![image](https://user-images.githubusercontent.com/15664251/61867212-92267280-aece-11e9-8d7f-436d6ed08d7b.png)

**Comment by fabiobarao94** [comment] 2019-07-25 11:01
i think i solved the problem, i just checked the option block all pop ups in this web site and now it works

**Comment by jspenguin2017** [comment] 2019-07-25 13:39
We don't support ABP. Can't reproduce with Nano. Closing as invalid.

**Closed by jspenguin2017** 2019-07-25 13:39 UTC
Labels: invalid
