### ISSUE TITLE
[Ads] spaste.com

### ISSUE THREAD

**Issue by Cyberavater** [NanoAdblocker/NanoFilters#505] opened 2020-05-22 15:26 UTC
Eg link: http://www.spaste.com/p/?c=GfuWpZ8829
After completing the captcha there are lots of ads video.

**Comment by llacb47** [comment] 2020-05-22 19:09
`http://fireworktv.com/`

`||fwcdn1.com^$script,3p` in case there are images or something else on the domain?

**Comment by jspenguin2017** [comment] 2020-05-22 22:46
Duplicate of https://github.com/NanoMeow/QuickReports/issues/1026

**Closed by jspenguin2017** 2020-05-22 22:46 UTC
