### ISSUE TITLE
9anime.is

### ISSUE THREAD

**Issue by InverIrisGlaive** [NanoAdblocker/NanoFilters#60] opened 2018-04-25 22:17 UTC
#### Environment (Required)

- Operating System and Version:  Microsoft Windows 10 Home, version 1709, build 16299.371
- Browser and Version: Google Chrome, Version 65.0.3325.181 (Official Build) (64-bit)
- Nano Adblocker Version: Nano Adblocker v1.0.0.43
- Nano Defender Version (Optional if you are not using it): Version 13.60

#### Your filter lists (Required)
From what I've seen, a lot of filter lists overlaps with nano-adblocker, from Adblock and what I'd used on Tampermonkey.

For Adblock:
AdBlock custom filters
EasyList
Adblock Warning Removal list (removes warnings about using ad blockers)
Antisocial filter list (removes social media buttons)
Cryptocurrency (Bitcoin) Mining Protection List
EasyPrivacy (privacy protection)
Fanboy's Annoyances (blocks in-page pop-ups, social media and related widgets, and other annoyances)
Malware protection
Screenshot: 
![image](https://user-images.githubusercontent.com/38737968/39275794-fda5e0c8-48bc-11e8-817a-0c9827dc7f4c.png)

On Tampermonkey:
It's Not Important (https://greasyfork.org/scripts/14720-it-s-not-important/code/It's%20Not%20Important.user.js) <--- the filterlist url
AAK-Cont Userscript for AdBlock, Adblock plus, etc
----> url: https://gitlab.com/xuhaiyang1234/AAK-Cont/raw/master/FINAL_BUILD/aak-cont-script-notubo.user.js
AAK-Cont Userscript for uBlock Origin,
--> url: https://gitlab.com/xuhaiyang1234/AAK-Cont/raw/master/FINAL_BUILD/aak-cont-script-ubo.user.js
Download Youtube Videos as MP4 (now obsolete, the devs didn't update the code and now it doesn't work, not sure if it's relevant) 
-----> https://greasyfork.org/scripts/1317-download-youtube-videos-as-mp4/code/Download%20YouTube%20Videos%20as%20MP4.user.js
Pinterest without Registration (again, obsolete, Dev didn't update, Pintrest over ran it about 5 months ago) 
-----> url: https://greasyfork.org/scripts/6325-pinterest-without-registration/code/Pinterest%20without%20registration.user.js
Youtube + (something to make youtube's UI more organized, but was notified that it wasn't compatible)
----> url: https://github.com/ParticleCore/Particle/raw/master/src/Userscript/YouTubePlus.user.js

List filters you have enabled or disabled from the default settings.
-->didn't disable any filter list from default
![image](https://user-images.githubusercontent.com/38737968/39275530-f5a1da04-48bb-11e8-886b-6144d414ca38.png)

#### Your custom filters (Required if you have any)
None.

**Comment by jspenguin2017** [comment] 2018-04-25 22:19
Duplicate of https://github.com/jspenguin2017/uBlockProtector/issues/914

**Closed by jspenguin2017** 2018-04-25 22:19 UTC
Labels: duplicate
