### ISSUE TITLE
Add title comment in filter.

### ISSUE THREAD

**Issue by gluons** [NanoAdblocker/NanoFilters#16] opened 2018-01-14 16:45 UTC
uBlock Origin doesn't display title. Please add title comment (`! Title: ...`) in your filter file.

![default](https://user-images.githubusercontent.com/4688092/34918387-8b493020-f984-11e7-8a68-b4f12f890628.PNG)

**Comment by jspenguin2017** [comment] 2018-01-14 16:57
Duplicate of #10

**Closed** 2018-01-14 16:56 UTC
Labels: duplicate

**Comment by gluons** [comment] 2018-01-14 16:59
OK. Thanks.
