### ISSUE TITLE
[Anti-adblock] thumpertalk.com

### ISSUE THREAD

**Issue by bikerbill2021** [NanoAdblocker/NanoFilters#442] opened 2020-01-05 23:50 UTC
I want to forward this post with the heads up that I am pretty much illiterate when it comes to any kind of computer things, I can figure very basic stuff out, but seriously, think of me as your grandparents and are trying to set up a computer for them.  I did my best in trying to give you all the info I can, but I'm missing some things like the screenshot of the "console", have no idea what that is, my f12 is my volume key on my mac.  Reddit directed me here to ask for help

https://thumpertalk.com/forums/

![Screen Shot 2020-01-05 at 4 42 46 PM](https://user-images.githubusercontent.com/59155366/71787987-462e3c80-2fdb-11ea-9203-d3f626894ac5.png)

I'm having an issue with anti ad blocker detection on a certain website I frequent, thumpertalk, it intermittently asks me to white list its site, with a countdown screen.

The site is tricky, it asks for you to whitelist it with a countdown, which you can hit back, and then click the link again and that page will be gone until it times out a while later again and will pop up when browsing the site, i want to say every 30 mins or so. 

Im running chrome version 79.0.3945.79 on my iMac with Sierra 10.12.4, I had ad block plus tied into tamper monkey anti adblock killer to help block ads and keep the annoying "please turn off your ad blocker" requests on certain sites I visit at bay. Recently I switched over to Nano adblocker version 1.0.0.130, with Nano defender version 15.0.0.170, as AAK was stating it was no longer supported, and ABP was bugging me to upgrade to their premium service.  Never had an issue with this site until I switched over to nano adblocker/defender.

filters
![Screen Shot 2020-01-05 at 4 47 43 PM](https://user-images.githubusercontent.com/59155366/71787985-42021f00-2fdb-11ea-83ac-db744f82dd6f.png)

**Comment by jspenguin2017** [comment] 2020-01-06 02:09
@okiehsch Annoyance, but quite hard to reproduce and fix. Offending code: 
```js
var _adBlockChecked = false;
googletag.cmd.push(function() {
    googletag.pubads().addEventListener('slotRenderEnded', function(event) {
        if (!_adBlockChecked) {
            _adBlockChecked = true;
            document.cookie = 'tt4_detectadblock_time=0; expires=Wed, 06 Jan 2021 01:42:23 UTC; path=/; domain=.thumpertalk.com; secure';

            dataLayer.push({
                'event': 'ads',
                'eventCategory': 'AdBlock',
                'eventAction': 'Ads Whitelisted',
                'eventLabel': 'Time',
                'eventValue': '15'
            });
        }
    });
});
```

Server side redirection once the cookie is not 0 for some time (15 to 30 minutes, not sure the exact number).

**Comment by jspenguin2017** [comment] 2020-01-06 02:12
Actually, deleting the cookie might work. 
`thumpertalk.com##+js(cookie-remover, tt4_detectadblock_time)`

**Comment by okiehsch** [comment] 2020-01-06 02:27
https://github.com/uBlockOrigin/uAssets/commit/b78d43b3861cab795702b864bf93a0950e57bdb2
I can't reproduce but if the filter works for you that is good enough for me.

**Comment by jspenguin2017** [comment] 2020-01-06 02:28
Yea, it takes a while to reproduce. I think the filter is working. Closing for now.

**Closed by jspenguin2017** 2020-01-06 02:28 UTC
Labels: confirmed

**Comment by bikerbill2021** [comment] 2020-01-06 04:06
Hey thanks guys I appreciate the help, is there something i need to do on my end?  or is it automatically added?

**Comment by okiehsch** [comment] 2020-01-06 05:00
You have to manually update your filter lists or wait until they auto update.
Click "Purge all caches" and then "Update now" to manually update.

**Comment by bikerbill2021** [comment] 2020-01-06 05:41
Thanks alot!  the site seems to be good now and not bugging me about white listing
