### ISSUE TITLE
[Annoyance, GDPR Wall] wp.pl and related domains

### ISSUE THREAD

**Issue by hawkeye116477** [NanoAdblocker/NanoFilters#362] opened 2019-06-19 19:14 UTC
### URLs where this issue occurs (Required)
`abczdrowie.pl,allani.pl,autokult.pl,dobramama.pl,dobreprogramy.pl,domodi.pl,echirurgia.pl,fotoblogia.pl,gadzetomania.pl,homebook.pl,jejswiat.pl,kafeteria.pl,kafeteria.tv,kardiolo.pl,komorkomania.pl,luxlux.pl,medycyna24.pl,mixer.pl,money.pl,nocowanie.pl,nerwica.com,o2.pl,open.fm,parenting.pl,pinger.pl,pogodnie.pl,pudelek.pl,pudelek.tv,pudelekx.pl,pytamy.pl,smaczneblogi.pl,samosia.pl,smog.pl,snobka.pl,superauto24.com,testwiedzy.pl,wp.pl`

### Screenshots (Required)
![Screenshot_20190619_205656](https://user-images.githubusercontent.com/19818572/59792697-13d61f80-92d5-11e9-9333-532a0795174a.png)

### Describe the issue (Optional if obvious)
GDPR on sites of WP Group, random element.

### Anything else you believe to be useful (Optional)
I think that for this you can only make clicking rule on button which contains text `PRZECHODZ`, but new resource is needed for this.

#### Environment (Required)

- Operating System and Version: Manjaro 18.0.4 Illyria
- Browser and Version: Vivaldi 2.5.1525.48
- Nano Adblocker Version: 1.0.0.115
- Nano Defender Version (Optional if you are not using it): n/a

#### Your filter lists (Required)
```
"https://raw.githubusercontent.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/master/adblock_social_filters/adblock_social_list.txt",
"https://raw.githubusercontent.com/PolishFiltersTeam/PolishRSSFilters/master/polish_rss_filters.txt",
 "https://raw.githubusercontent.com/PolishFiltersTeam/PolishAnnoyanceFilters/master/PPB.txt",
"https://raw.githubusercontent.com/PolishFiltersTeam/KAD/master/KAD.txt",
    "POL-2",
    "POL-0",
    "plowe-0",
    "nocoin-0",
    "fanboy-social",
    "malware-1",
    "malware-0",
    "easyprivacy",
    "awrl-0",
    "ublock-unbreak",
    "ublock-abuse",
    "ublock-privacy",
    "ublock-badware",
    "ublock-annoyances",
    "ublock-filters",
    "nano-whitelist",
    "nano-annoyance",
    "nano-filters"
```

**Comment by jspenguin2017** [comment] 2019-06-20 01:25
Reproduced with VPN.

**Comment by jspenguin2017** [comment] 2019-06-20 01:27
Marking as under consideration because there's two buttons. See also: https://github.com/NanoAdblocker/NanoFilters/issues/124#issuecomment-403667249

**Closed** 2019-06-26 18:40 UTC
Labels: geolock, wontfix
