### ISSUE TITLE
Reddit Alpha PROMOTED

### ISSUE THREAD

**Issue by Emilylove00** [NanoAdblocker/NanoFilters#26] opened 2018-02-04 09:24 UTC
https://imgur.com/a/9QNgH

For some days now reddit show PROMOTED content.

Its the new reddit design*

**Comment by jspenguin2017** [comment] 2018-02-04 16:28
Need test link.

**Comment by Emilylove00** [comment] 2018-02-05 06:58
Only link i know is this. https://www.reddit.com/r/redesign/ I was asked and joined the new design.

**Comment by Emilylove00** [comment] 2018-02-05 07:00
Op! found it! https://alpha.reddit.com/

**Comment by jspenguin2017** [comment] 2018-02-05 13:32
Can't reproduce. Closing as invalid due to the lack of template.

**Closed by jspenguin2017** 2018-02-05 13:32 UTC
Labels: invalid
