### ISSUE TITLE
NSFW! [Anti-adblock] avgle.com

### ISSUE THREAD

**Issue by sadtango289** [NanoAdblocker/NanoFilters#562] opened 2020-09-22 14:26 UTC
### URLs where this issue occurs (Required)

https://avgle.com/video/NyDTYT3n2TQ/fc2%E7%9C%9F%E5%AF%A6%E7%B4%A0%E4%BA%BA%E7%B2%BE%E9%81%B8-%E4%B8%BB%E4%BA%BA-%E6%82%A8%E5%9B%9E%E4%BE%86%E4%BA%86-%E5%AE%B6%E8%A3%A1%E6%9C%89%E5%85%A9%E5%80%8B%E5%A5%B3%E5%83%95-%E7%9C%9F%E7%9A%84%E5%A5%BD%E5%B9%B8%E7%A6%8F%E5%94%B7-%E5%A7%8A%E5%A7%8A%E8%B2%A0%E8%B2%AC%E6%8E%8C%E9%8F%A1-%E8%AE%93%E6%88%91%E8%83%BD%E5%A5%BD%E5%A5%BD%E5%9C%B0%E6%84%9B%E6%92%AB%E5%A6%B9%E5%A6%B9

### Screenshots (Required)

<details>

Turn off Nano . Video is play good 
 ![Alt Text](https://www.upsieutoc.com/images/2020/09/22/Capturee3dac28e3fa5900f.png)
Turn on Nano . The loading circle ( in red ) keeps round and round . Video is not play. 
 ![Alt Text](https://www.upsieutoc.com/images/2020/09/22/Capture1.png)

</details>

### Screenshot of console (Required, press `F12` to open the console)

<details>

 ![Alt Text](https://www.upsieutoc.com/images/2020/09/22/Capture3f6159c02347b6c4.png)

</details>

#### Environment (Required)

- Operating System and Version:  Win 7  SP1 Untimate 64 bit
- Browser and Version: CocCoc 89.0.124 32 bit ( Vietnam ) 
- Nano Adblocker Version: 1.0.0.153
- Nano Defender Version (Optional if you are not using it): 15.0.0.205

#### Your filter lists (Required)
 Ticked ALL filters

#### Your custom filters (Required if you have any)

None
#### Your other extensions (Required if you have any)

![Alt Text](https://i.imgur.com/icfxUeF.png)

**Comment by jspenguin2017** [comment] 2020-09-22 14:38
Duplicate of https://github.com/NanoMeow/QuickReports/issues/496

**Closed by jspenguin2017** 2020-09-22 14:38 UTC
Labels: duplicate

**Comment by sadtango289** [comment] 2020-09-23 02:53
SOLVED : Uncheck "Region Region, language Filter" . My bad  :-/
