### ISSUE TITLE
[Anti-adblock] foxnews.com

### ISSUE THREAD

**Issue by ansul1001** [NanoAdblocker/NanoFilters#420] opened 2019-11-08 16:06 UTC
### URLs where this issue occurs (Required)
https://www.foxnews.com/politics/marie-yovanovitch-ukraine-emails-house-democrat-staffer-delicate-issue

### Screenshots (Required)
![Capture fox](https://user-images.githubusercontent.com/49883320/68490889-a3d22280-01fe-11ea-991f-7106ef6927e4.JPG)

### Screenshot of console (Required, press `F12` to open the console)

[Nano] Nano Defender Activated :: github.com
chrome-extension://ggolfgbegefeeoocgjbmkembbncoadlb/content/rules-common.js:295 [Nano] Excluded :: uBO-Extra
www.google-analytics.com/collect:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
/NanoAdblocker/NanoFilters/used_by_count:1 Failed to load resource: the server responded with a status of 406 (Not Acceptable)
page_view:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
api.github.com/_private/browser/stats:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

### Describe the issue (Optional if obvious)

fox new detecting ad blocker

#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by jspenguin2017** [comment] 2019-11-08 16:31
Duplicate of https://github.com/NanoMeow/QuickReports/issues/2240

**Closed by jspenguin2017** 2019-11-08 16:31 UTC
