### ISSUE TITLE
kissanime.ru

### ISSUE THREAD

**Issue by juppaluri** [NanoAdblocker/NanoFilters#116] opened 2018-06-29 03:46 UTC
### URLs where this issue occurs (Required)

http://kissanime.ru/Anime/Inazuma-Eleven/Episode-127?id=34228&s=rapidvideo

### Screenshots (Required)
![screen shot 2018-06-28 at 11 39 22 pm](https://user-images.githubusercontent.com/12588760/42072044-950f33b4-7b2c-11e8-8f8a-ace288fded00.png)

### Screenshot of console (Required, press `F12` to open the console)
![screen shot 2018-06-28 at 11 41 07 pm](https://user-images.githubusercontent.com/12588760/42072085-c6337af4-7b2c-11e8-8a00-834d96637678.png)

### Describe the issue (Optional if obvious)
The site cannot be used.

### Reproduction Steps (Optional if trivial)

Accessing the site with an adblocker should be enough to trigger it.

#### Environment (Required)

- Operating System and Version: macOS Sierra 10.12.4
- Browser and Version: Firefox 61.0
- Nano Adblocker Version: uBlock Origin 1.12.10
- Nano Defender Version (Optional if you are not using it): 15.0.0.0

#### Your custom filters (Required if you have any)
Nano defender integration
Nano filters
Nano filters - Whitelist

**Comment by mapx-** [comment] 2018-06-29 06:13
update `ublock filters`, test again

**Comment by jspenguin2017** [comment] 2018-06-29 13:18
Duplicate of https://github.com/uBlockOrigin/uAssets/issues/2708

**Closed by jspenguin2017** 2018-06-29 13:18 UTC
Labels: duplicate

**Comment by juppaluri** [comment] 2018-06-29 14:42
I apologize for my duplicate, thank you for the help.
