### ISSUE TITLE
[Ads] anitoki.com

### ISSUE THREAD

**Issue by RaveN0X87** [NanoAdblocker/NanoFilters#341] opened 2019-05-26 18:59 UTC
example link :
```
https://asiatoday.online/click?s_id=5ceae1c914b25&b_id=174&n_id=0&pos=1&temp=main&news_type=main 
https://asiatoday.online/click?s_id=5ceae1c914b25&b_id=181&n_id=0&pos=2&temp=main&news_type=main
https://asiatoday.online/click?s_id=5ceae1c914b25&b_id=126&n_id=0&pos=3&temp=main&news_type=main
https://asiatoday.online/click?s_id=5ceae1c914b25&b_id=75&n_id=0&pos=4&temp=main&news_type=main
https://asiatoday.online/click?s_id=5ceae1c914b25&b_id=114&n_id=0&pos=5&temp=main&news_type=main
```

**Comment by jspenguin2017** [comment] 2019-05-26 19:12
Which part of it do you consider to be ads? I don't see any obvious ones.

**Comment by RaveN0X87** [comment] 2019-05-26 19:55
top of the web
![screencapture-anitoki-2019-05-27-02_52_18](https://user-images.githubusercontent.com/39649317/58386486-9519f980-802a-11e9-9a1c-ec411b232db5.png)

**Comment by jspenguin2017** [comment] 2019-05-26 20:26
@RaveN0X87 So `anitoki.com` is the real test link? Make sure to fill the template next time.

**Comment by jspenguin2017** [comment] 2019-05-26 20:26
@okiehsch Test: `https://anitoki.com/`. Also, the entire `asiatoday.online` domain can probably go.

**Comment by okiehsch** [comment] 2019-05-26 20:41
I can't reproduce the screenshot and I don't see any `asiatoday.online` requests on my end.

**Comment by jspenguin2017** [comment] 2019-05-26 20:46
So that goes into EasyList?

**Comment by okiehsch** [comment] 2019-05-26 20:48
Yes but I doubt the ads in the screenshot of the OP willbe fixed by that filter.

**Comment by okiehsch** [comment] 2019-05-26 20:52
Actually the banner is already blocked if I enable the indonesian regional filter.

**Comment by jspenguin2017** [comment] 2019-05-26 21:02
The website is in English though.

**Comment by okiehsch** [comment] 2019-05-26 21:06
Parts of it, I would argue that it is an indonesian website.
Go to any video, which is the main content of the site, for example
`https://anitoki.com/2018/09/yuragi-sou-no-yuuna-san-12-subtitle-indonesia/`
and you will see that the synopsis of the episodes are in indonesian.

**Comment by jspenguin2017** [comment] 2019-05-26 21:12
Hum... Alright, closing for now.

**Closed by jspenguin2017** 2019-05-26 21:12 UTC
Labels: cannot reproduce
