### ISSUE TITLE
[Ads] dobreprogramy.pl

### ISSUE THREAD

**Issue by KonoromiHimaries** [NanoAdblocker/NanoFilters#3] opened 2017-12-14 03:39 UTC
`https://www.dobreprogramy.pl/`

![dobreprogramy - portal nie tylko o oprogramowaniu](https://user-images.githubusercontent.com/5884000/33974410-88726548-e088-11e7-9bbb-a03b9e4f5e43.png)

my filters
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

Nano Adblocker 1.0.0.12
Nano Defender 13.0
Chrome 63.0.3239.84

**Comment by jspenguin2017** [comment] 2017-12-14 03:41
Wow, it's has anti-hiding logic built in... Eh...

**Comment by elypter** [comment] 2017-12-14 20:13
i just came across something equally nasty:
http://tooladblockerext.com/ff/?_subid=20k3d7e46d044svolcd&_token=uuid_20k3d7e46d044svolcd_20k3d7e46d044svolcd5a32d6f6f38d84.59487681

it just exist to fuck with people who have an adblocker out of pure spitefulness. they want you to install some malware but you even cant because they trigger a firefox reload warning that just pops up again after you close it just like it used to be with alert() boxes. i cant believe that mozilla fixed one but not the other, especially if you consider how often they redid the whole user interface. i cant believe this is still possible with browsers in 2017. fortunately i have a slow pc so i managed to close the tab by clicking really fast. warning: you might have to kill the browser and disable the network to prevent this shit from loading again on session restore.

fortunately it can be blocked easily. i wish i could not just block them but DDOS them with the power of a thousand matrioshka brains.
||tooladblockerext.com^$document

**Comment by jspenguin2017** [comment] 2017-12-14 20:22
Well, Firefox only, we'll worry about that later. 
Stay on topic, don't post unrelated information.

**Comment by jspenguin2017** [comment] 2017-12-16 02:34
Looks like it's fixed in polish filters. 
![image](https://user-images.githubusercontent.com/7283682/34066636-c99ff5ac-e1ce-11e7-8b46-def7a40355ee.png)

**Comment by mat41997** [comment] 2017-12-16 02:37
i know.
that not works in 100%

1/6 times i have this baner back

**Comment by jspenguin2017** [comment] 2017-12-16 02:39
Yea, it's breaking though cosmetic filter sometimes... It feels like a bug in uBO. I'll investigate further later.

**Comment by jspenguin2017** [comment] 2017-12-16 03:30
@okiehsch want to have a look at this one? kinda need a hand here.

**Comment by okiehsch** [comment] 2017-12-16 03:39
````
dobreprogramy.pl##body > *:matches-css(background-image: /data:image\/(gif|jpg|jpeg|png);base64,/):matches-css(position: fixed)
````
fixes the issue reliably on my end, so I really can't help, maybe it is a Windows issue, I only have access to Linux (Manjaro) at the moment.

**Comment by jspenguin2017** [comment] 2017-12-16 03:44
What's the version of your uBO?

**Comment by okiehsch** [comment] 2017-12-16 03:47
1.14.20

**Comment by okiehsch** [comment] 2017-12-16 03:51
I see the chrome webstore has 1.14.22, but it won't updat at the moment.

**Comment by jspenguin2017** [comment] 2017-12-16 03:53
How come it won't update? Can gorhill choose who can update?

**Comment by okiehsch** [comment] 2017-12-16 03:57
I think he does something like 10% the first day 30% the day after and so forth.

**Comment by jspenguin2017** [comment] 2017-12-16 04:00
How does he do that? I don't see that option in my Web Store dashboard...

**Comment by okiehsch** [comment] 2017-12-16 04:03
You have to ask him, but I just tried spam clicking "update" and now I have successfully updated to
1.14.22.

**Comment by jspenguin2017** [comment] 2017-12-30 22:09
The ads does flash once, but I'd say it's good enough. Marking as fixed unless you have further concerns.

**Comment by userOperaFF** [comment] 2018-01-08 23:22
Comeback in new place https://github.com/easylist/easylist/issues/819

Possible now see for all PL users with default lists.

**Comment by jspenguin2017** [comment] 2018-01-09 22:36
Is this being handled in the regional filter?

**Comment by KonoromiHimaries** [comment] 2018-01-09 22:50
@jspenguin2017 yes, in latest update and only for chrome

**Comment by userOperaFF** [comment] 2018-01-09 23:09
On Firefox I must use 17 cosmetic simple filters to hide this.

**Comment by Martina-Neumayer** [comment] 2018-01-12 05:09
Seems that they changed again the page code.. ;P

![screenshot_3](https://user-images.githubusercontent.com/13028529/34860541-866d3d76-f75e-11e7-80d9-07924e5c0cd1.png)

And is one more issue.. Turning Nano Adblocker ON disables commenting possibilities on their page.
Here I just want to respond to user "hins" and no way to do that if my Nano is on.

![screenshot_4](https://user-images.githubusercontent.com/13028529/34860603-03e0dc2c-f75f-11e7-958e-2e0ecaa78b28.png)

Even added those filters won't help anymore.. http://wklejto.pl/320680

**Comment by KonoromiHimaries** [comment] 2018-01-12 11:56
![2018-01-12 12_55_01-nowoczesny system operacyjny uruchomiono na komputerze z 1993 roku - dobreprogra](https://user-images.githubusercontent.com/5884000/34874105-0082234a-f798-11e7-9c88-32f5df1bab78.png)

**Comment by jspenguin2017** [comment] 2018-01-12 13:32
Is this being handled in regional filters? I'l quite busy these days so it can take a while. 

cc @mapx- @okiehsch

**Comment by Martina-Neumayer** [comment] 2018-01-12 14:00
@jspenguin2017 Sadly but no is not. Not yet as far as I see.
No problemo.. this is not asap-to-fix issue ;)

**Comment by mapx-** [comment] 2018-01-12 19:35
test these filters
```
||wpimg.pl^$domain=dobreprogramy.pl
@@||dobreprogramy.pl^$generichide
@@||static.criteo.net/js/ld/publishertag.js$script,domain=dobreprogramy.pl
```

**Comment by Martina-Neumayer** [comment] 2018-01-13 08:29
@mapx- Thnx :) Ads are mostly gone. Mostly because if you turn OFF and back ON blocking they appear again, but only until you hit "shift+F5" to refresh the page. So.. lets say is ok with them.
But the problem with the comments still remains.
You have to click several times in the "Odpowiedz" (Reply) option so that the commenting window allows you to enter text.
Like on this movie.. https://streamable.com/r980b

**Comment by mapx-** [comment] 2018-01-13 09:15
No issue for me (in uBo 1.14.23.100 chrome 64): I enabled the 2 polish lists + (only my) filters above and the comment stuff is ok

**Comment by Martina-Neumayer** [comment] 2018-01-13 10:57
@mapx- Tested now like You.. only Nano + 2 PL lists + only your filters from above. No changes.
Can be somehow a Nano related issue?

**Comment by mapx-** [comment] 2018-01-13 11:18
install uBo and test again .. even if nano is uBo with some changes

**Comment by jspenguin2017** [comment] 2018-01-13 16:04
I can't reproduce the problem neither, try clearing your browser cache.

**Comment by Martina-Neumayer** [comment] 2018-01-14 08:17
I did it before I wrote here.

**Comment by KonoromiHimaries** [comment] 2018-01-14 12:20
@Martina-Neumayer try it format your computer, this is 100% work.

**Comment by Martina-Neumayer** [comment] 2018-01-14 15:38
@KonoromiHimaries Well.. You can also try to jump trough the window with your "tips" like that my friend.
So.. just spare me this please.

**Comment by LArtCrime** [comment] 2018-01-14 16:12
On Firefox no works perfect - [#357333491 (comment)](/NanoAdblocker/NanoFilters/issues/3#issuecomment-357333491 "#3 (comment), [Ads] dobreprogramy.pl") - I must refresh any new opened article to hide ad.

No worka clear cache and any other options refresh / create new profile Firefox.

**Comment by jspenguin2017** [comment] 2018-01-14 16:19
The issue in the regional filter repo is closed, is this resolved?

**Comment by jspenguin2017** [comment] 2018-01-14 16:21
It works on Firefox for me as well. 
![image](https://user-images.githubusercontent.com/7283682/34918199-45b1e502-f90c-11e7-87c4-a8578b40f52b.png)

**Comment by Martina-Neumayer** [comment] 2018-01-17 08:06
@mapx- Sadly your fix with those..

> ||wpimg.pl^$domain=dobreprogramy.pl
@@||dobreprogramy.pl^$generichide
||static.criteo.net/js/ld/publishertag.js$script,redirect=noopjs,domain=dobreprogramy.pl

Don't work anymore. All their ads have appeared again.

**Comment by LArtCrime** [comment] 2018-01-17 08:39
@mapx- And now broke forum in Firefox (see empty elements and texts "R E K L A M A" ("A d v i s e m e n t s").

**Comment by mapx-** [comment] 2018-01-17 13:33
test
```
@@||dobreprogramy.pl^$generichide
@@||static.criteo.net/js/ld/publishertag.js$script,domain=dobreprogramy.pl
@@||amp.services^$script,domain=dobreprogramy.pl
@@||googletagservices.com^$script,domain=dobreprogramy.pl
@@||securepubads.g.doubleclick.net^$script,domain=dobreprogramy.pl
```

**Comment by Martina-Neumayer** [comment] 2018-01-17 13:43
@mapx- Thank You :) Works great again :+1:

**Comment by mapx-** [comment] 2018-01-17 21:20
someone could test if site's funtionalities are broken using one of these filters ?

`||dobreprogramy.pl^$inline-script`
or
`||dobreprogramy.pl^$csp=script-src 'unsafe-eval' * blob: data:`

**Comment by KonoromiHimaries** [comment] 2018-01-17 21:33
@mapx- comment section
![img](https://user-images.githubusercontent.com/5884000/35068101-560aeb98-fbd6-11e7-92bf-0dd2d69ae8ff.png)

**Comment by okiehsch** [comment] 2018-01-17 21:46
Instead of disabling inline-script how about just adding
`dobreprogramy.pl##script:inject(abort-on-property-write.js, Math.floor)?

**Comment by KonoromiHimaries** [comment] 2018-01-17 22:31
@okiehsch programs sub site

![2018-01-17-programy dla windows - dobreprogramy](https://user-images.githubusercontent.com/5884000/35070734-95c39e8a-fbde-11e7-8775-c4a838d44e36.png)
`https://www.dobreprogramy.pl/Programy,Windows.html`

**Comment by okiehsch** [comment] 2018-01-17 22:53
`dobreprogramy.pl##script:inject(abort-on-property-write.js, Math.random)` has less layout breakage.

If you do not want to have **any** breakage of any kind, you will have to use exception filters. or even better, use Firefox with uBO 1.14.25rc1 and add
`dobreprogramy.pl##^script:has-text(outerMostParent)`

**Comment by jspenguin2017** [comment] 2018-01-17 23:02
The latest Nano Adblocker has HTML filtering enabled. I can make the rule work on Chromium, but it won't be configurable.

**Comment by mapx-** [comment] 2018-01-17 23:14
what about 
`dobreprogramy.pl##script:inject(abort-current-inline-script.js, String.fromCharCode)`

?

**Comment by okiehsch** [comment] 2018-01-17 23:19
`dobreprogramy.pl##script:inject(abort-current-inline-script.js, Math.random, outerMostParent)`
is probably the better solution, less chance of site breakage, but they both work on my end.

**Comment by KonoromiHimaries** [comment] 2018-01-18 16:29
@okiehsch @mapx- ad has back

**Comment by Martina-Neumayer** [comment] 2018-01-18 16:29
At my side opera-crap is stil there.. tested with both filtering methods.

**Comment by mapx-** [comment] 2018-01-18 18:35
ugly "fix"
`@@$script,xmlhttprequest,domain=dobreprogramy.pl`

**Comment by jspenguin2017** [comment] 2018-01-18 20:01
From my past experience, if the fight comes to this point, we have to either give up or make a proprietary rule.

**Comment by gwarser** [comment] 2018-01-19 08:33
If you can live with large blank spaces: `||dobreprogramy.pl^$csp=img-src 'self' *.dpcdn.pl`

**Comment by Martina-Neumayer** [comment] 2018-01-19 16:33
Yeap.. is okay now. BTW.. this text "..you win.." is a bit.. hmm.. infantile imho, but ok.
The main thing - is working and my cpu is not killed anymorw by all their ads-scripts-acrobatics.
Thank You all :kiss:

**Comment by KonoromiHimaries** [comment] 2018-01-22 13:39
@okiehsch ping

**Comment by jspenguin2017** [comment] 2018-01-22 15:38
Told you. There is no point in continuing this silly fight.

**Comment by Martina-Neumayer** [comment] 2018-01-22 19:11
Well.. I think is time for me to say: "farewell dp". Without turned on Nano this page kills my cpu and thus also battery.

**Comment by mapx-** [comment] 2018-01-22 19:15
@Martina-Neumayer  did you try the filter posted by @gwarser  above ?

test also
`||dobreprogramy.pl^$csp=style-src *`

probably some graphic annoyance will appear but not the huge crap on top

**Comment by Martina-Neumayer** [comment] 2018-01-22 19:38
@mapx- Yes, I tried them, but without success

**Comment by mapx-** [comment] 2018-01-22 19:46
What do you mean ? I still see the comments, the ads are gone ?!

**Comment by Martina-Neumayer** [comment] 2018-01-22 19:54
@mapx- I mean, ads appear after a while and the cpu killer is again there.

**Comment by mapx-** [comment] 2018-01-22 19:54
Did you test in uBo too ?

**Comment by KonoromiHimaries** [comment] 2018-01-22 19:57
@mapx- site has broken if i use that rule
![2018-01-22-dobreprogramy - portal z legalnym oprogramowaniem](https://user-images.githubusercontent.com/5884000/35241408-b1596a9a-ffb6-11e7-98a5-5d797263a1db.png)
`https://www.dobreprogramy.pl/Wideo.html`

**Comment by mapx-** [comment] 2018-01-22 20:00
yeah, you wont see the preview images but then the videos are ok, right ?

or use the other csp filter ( `$csp=img-src` )

**Comment by KonoromiHimaries** [comment] 2018-01-22 20:06
@mapx- if i use that rule `||dobreprogramy.pl^$csp=img-src`

them i have this
![2018-01-22-lab - dobreprogramy](https://user-images.githubusercontent.com/5884000/35241826-1318905c-ffb8-11e7-8968-4afe1758d828.png)

**Comment by mapx-** [comment] 2018-01-22 20:09
the filter proposed above is:
`||dobreprogramy.pl^$csp=img-src 'self' *.dpcdn.pl`

**Comment by Martina-Neumayer** [comment] 2018-01-22 20:10
@mapx- No, only in Nano. I don't have time to migrate from one to another and back ;)

**Comment by KonoromiHimaries** [comment] 2018-01-22 20:12
@mapx- logo in top
![2018-01-22-wszystkie aktualnosci - dobreprogramy](https://user-images.githubusercontent.com/5884000/35242122-f7af0bc4-ffb8-11e7-9600-81e6024e65b3.png)
`https://www.dobreprogramy.pl/Aktualnosci,Wszystkie,0.html`

**Comment by mapx-** [comment] 2018-01-22 20:17
yeah, I Already said, there will be some graphic issues. The style-src seems better (blocking almost totally the huge ad at the top) but is your choice ..

**Comment by okiehsch** [comment] 2018-01-22 20:25
````
dobreprogramy.pl##script:inject(abort-on-property-write.js, Math.random)
forum.dobreprogramy.pl#@#script:inject(abort-on-property-write.js, Math.random)
````
will have the least breakage in my opinion.

**Comment by Martina-Neumayer** [comment] 2018-01-22 20:30
Is not my choice. Is the choice of the EDV from the company where I work. This laptop is their equipment.
I only use it.
Okay.. I have blocked now two domains (criteo and wpimg) entirety on my router. Cpu killing is gone and with your filter the page looks like this..

![screenshot_2](https://user-images.githubusercontent.com/13028529/35242881-4492b4de-ffbb-11e7-8e4d-153563ec411b.png)

BTW.. Where did You get this nice dark theme for it?

**Comment by KonoromiHimaries** [comment] 2018-01-22 20:33
@okiehsch maybe not
![2018-01-22-dobreprogramy - portal nie tylko o oprogramowaniu](https://user-images.githubusercontent.com/5884000/35243071-eb7b5832-ffbb-11e7-89a5-4cb59a204730.png)

**Comment by okiehsch** [comment] 2018-01-22 20:40
Well, I sai least, breakage, not no breakage, they changed their code from last week,
`dobreprogramy.pl##script:inject(abort-on-property-write.js, Math.random)` will now also break comments, which was not the case at [this](https://github.com/NanoAdblocker/NanoFilters/issues/3#issuecomment-358476831) point.

**Comment by okiehsch** [comment] 2018-01-22 21:39
````
dobreprogramy.pl##script:inject(addEventListener-defuser.js, DOMContentLoaded, removeEventListener)`
````

**Comment by okiehsch** [comment] 2018-01-22 21:44
````
dobreprogramy.pl##script:inject(addEventListener-defuser.js, DOMContentLoaded, removeEventListener)
````

**Comment by KonoromiHimaries** [comment] 2018-01-24 18:48
ping @okiehsch

**Comment by okiehsch** [comment] 2018-01-24 21:06
At a quick glance I don't see a way to fix the issue with Chrome without breaking stuff and I will not spend much time finding a fix, if possible, that will be obsolete in 48 hours.

By the way, the site has no issue with Firefox on my end.

**Closed** 2018-02-07 11:12 UTC
