### ISSUE TITLE
[Anti-adblock] gameguardian.net

### ISSUE THREAD

**Issue by ichankhi** [NanoAdblocker/NanoFilters#200] opened 2018-10-23 08:30 UTC
https://gameguardian.net

image: https://prnt.sc/l9c4qy

**Comment by jspenguin2017** [comment] 2018-10-23 14:02
Cannot reproduce. Marking as invalid as you have not filled the template. 
![image](https://user-images.githubusercontent.com/7283682/47365983-f3988700-d699-11e8-9c80-8694f25c9aaa.png)

**Closed by jspenguin2017** 2018-10-23 14:02 UTC
Labels: invalid
