### ISSUE TITLE
[Anti-adblock] vidstream.top 

### ISSUE THREAD

**Issue by YASINEDr** [NanoAdblocker/NanoFilters#379] opened 2019-07-22 17:30 UTC
### URLs where this issue occurs (Required)

https://vidstream.top/f/ox4RpNYD2L/?vclid=ad1428f544f63fd76ed29e4dcb04b4a8e1509c405dc354238e7e91d9FUUUclshVcUFUcFDMtiynSxhhkwIzUhQhFCcFcUczdoUcUFUctttUwjhhcUSLxDrUcUf

### Screenshots (Required)

![screenshot-vidstream top-2019 07 22-18_26_40](https://user-images.githubusercontent.com/34688076/61651895-bc99e500-acae-11e9-8202-35b90dbdb52b.png)

#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by jspenguin2017** [comment] 2019-07-23 00:54
Duplicate of https://github.com/NanoAdblocker/NanoFilters/issues/377

**Closed by jspenguin2017** 2019-07-23 00:54 UTC
Labels: duplicate
