### ISSUE TITLE
[Anti-adblock] reevown.com

### ISSUE THREAD

**Issue by carlosmg2** [NanoAdblocker/NanoFilters#404] opened 2019-09-25 09:36 UTC
### URLs where this issue occurs (Required)

https://reevown.com

### Screenshots (Required)
with nano OFF
![nano off](https://user-images.githubusercontent.com/5909896/65588099-35573f00-df87-11e9-8faf-ed3f2231161c.png)

with nano ON (and putting mouse over Download File button)
![nano on](https://user-images.githubusercontent.com/5909896/65588138-42742e00-df87-11e9-9d80-2563938af0e2.png)

### Screenshot of console (Required, press `F12` to open the console)

![console](https://user-images.githubusercontent.com/5909896/65588887-8451a400-df88-11e9-945d-f5153676f2a7.png)

### Describe the issue (Optional if obvious)

web detects adblock

### Reproduction Steps (Optional if trivial)

with NanoAdblock enabled when you put cursor over the Download File button  Antiadblock message appears.

#### Environment (Required)

- Operating System and Version: Windows 10 Pro x64
- Browser and Version: Chrome 76.0.3809.132 (Build oficial) (64 bits)
- Nano Adblocker Version: 1.0.0.126
- Nano Defender Version (Optional if you are not using it): 15.0.0.168

#### Your filter lists (Required)

![image](https://user-images.githubusercontent.com/5909896/65588717-481e4380-df88-11e9-9f72-dd69ce7f471d.png)

**Comment by jspenguin2017** [comment] 2019-09-26 03:56
Duplicate of https://github.com/NanoMeow/QuickReports/issues/1733

**Closed by jspenguin2017** 2019-09-26 03:56 UTC
