### ISSUE TITLE
bild.de

### ISSUE THREAD

**Issue by tycho47** [NanoAdblocker/NanoFilters#140] opened 2018-07-18 08:51 UTC
### URLs where this issue occurs (Required)
https://www.bild.de

#### Environment (Required)

- Operating System and Version: 
- Browser and Version: 
- Nano Adblocker Version: 
- Nano Defender Version (Optional if you are not using it):

**Comment by jspenguin2017** [comment] 2018-07-18 13:12
Cannot reproduce. Closing as invalid as you did not fill the template.

**Closed by jspenguin2017** 2018-07-18 13:12 UTC
Labels: invalid
